chrome.storage.local.setAccessLevel({accessLevel:'TRUSTED_CONTEXTS'});
let serial=Promise.resolve(),lastError='',lastCapture=0;const serialized=fn=>{const result=serial.then(fn);serial=result.catch(()=>{});return result};
const cfg=async()=>(await chrome.storage.local.get('config')).config||{url:'http://127.0.0.1:48721',username:''};
async function req(c,route,options={}){const r=await fetch(c.url+route,{...options,headers:{Authorization:'Bearer '+(c.token||''),...options.headers},signal:AbortSignal.timeout(20000)}).catch(()=>{throw Error('服务连接失败，请检查网络；本机联动需保持观影运行')});if(!r.ok){let error;try{error=(await r.json()).error}catch{}throw Error(error||'服务连接失败')}return r}
async function syncQueue(){const c=await cfg(),{queue=[]}=await chrome.storage.local.get('queue');if(!queue.length)return;if(!c.token)throw Error('请先登录，待同步笔记仍保存在此浏览器');const records=(await(await req(c,'/records')).json()).records,byKey=new Map(records.map(r=>[r.key,r]));for(const entry of [...queue]){if(entry.userId!==c.userId)throw Error('待同步笔记属于另一账号，请恢复原账号');for(const shot of entry.note.shots){const r=await fetch(shot.data);await req(c,'/assets/'+shot.image,{method:'PUT',body:await r.arrayBuffer()})}const note={...entry.note,shots:entry.note.shots.map(({data,...s})=>s)},itemKey='item:'+entry.item.id,noteKey='note:'+note.id,existing=byKey.get(itemKey);if(existing?.deleted)throw Error('此影片已在另一设备移除，笔记留在待同步列表；请先恢复影片档案');const batch=[];if(!existing)batch.push({key:itemKey,revision:0,value:entry.item});else if((entry.item.lastPlayed||0)>(existing.value.lastPlayed||0)){const incoming=entry.item.episodes[0],item={...existing.value,lastPlayed:entry.item.lastPlayed,episodes:existing.value.episodes.map(e=>e.id===incoming.id?{...e,position:incoming.position,duration:incoming.duration||e.duration}:e)};batch.push({key:itemKey,revision:existing.revision,value:item})}const old=byKey.get(noteKey);if(old){if(old.deleted||JSON.stringify(old.value)!==JSON.stringify(note))throw Error('待同步笔记与服务版本冲突，请保留待同步记录并在桌面处理')}else batch.push({key:noteKey,revision:0,value:note});if(batch.length){const result=await(await req(c,'/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:batch})})).json();for(const r of result.accepted)byKey.set(r.key,r);if(result.conflicts.length)throw Error('同步时出现版本冲突，已保留待同步笔记，请重试')}queue.splice(queue.findIndex(x=>x.note.id===entry.note.id),1);await chrome.storage.local.set({queue})}lastError=''}
async function handle(m,sender){
 const trusted=sender.url?.startsWith(chrome.runtime.getURL('')),web=sender.tab&&/^https:\/\/www\.bilibili\.com\/(video\/|bangumi\/play\/)/.test(sender.url||'');if(!trusted&&!web)throw Error('来源未授权');
 if(m.type==='status'){const c=await cfg(),{queue=[]}=await chrome.storage.local.get('queue');return {url:c.url,username:c.username,connected:!!c.token,remote:c.url.startsWith('https:'),pending:queue.length,error:lastError}}
 if(m.type==='login'){if(!trusted)throw Error('请在插件图标中登录');const input=m.input,u=new URL(input.url);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))throw Error('在线服务必须使用 HTTPS');const c=await cfg(),url=u.origin+u.pathname.replace(/\/$/,'');const body=await(await req({url},'/auth/'+(input.register?'register':'login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)})).json();if(c.userId&&(c.userId!==body.user.id||c.url!==url)){const {queue=[]}=await chrome.storage.local.get('queue');if(!input.migrate||queue.length)throw Error('请先同步完待同步笔记，并勾选改连新服务；避免笔记混入其他账号')}await chrome.storage.local.set({config:{url,username:body.user.username,userId:body.user.id,token:body.token}});await syncQueue();return true}
 if(m.type==='logout'){if(!trusted)throw Error('请在插件图标退出');const c=await cfg();try{await req(c,'/auth/logout',{method:'POST'})}catch{}c.token='';await chrome.storage.local.set({config:c});return true}
 if(m.type==='retry'){await syncQueue();return true}
 if(m.type==='save'){if(!web)throw Error('请在视频页面保存');const c=await cfg();if(!c.userId)throw Error('请先点击浏览器插件图标登录');const n=m.note,i=m.item;if(!n||!i||n.itemId!==i.id||!['quote','shot','frame'].includes(n.kind)||!Array.isArray(n.shots)||n.shots.length>20||!Number.isFinite(n.start)||!Number.isFinite(n.end)||n.start<0||n.end<n.start||n.shots.some(s=>typeof s.data!=='string'||!s.data.startsWith('data:image/png;base64,')||s.data.length>32000000)||JSON.stringify(m).length>60000000)throw Error('笔记格式或图片大小无效');const {queue=[]}=await chrome.storage.local.get('queue');queue.push({userId:c.userId,item:i,note:n});await chrome.storage.local.set({queue});try{await syncQueue();return {synced:true}}catch(e){lastError=e.message;return {synced:false,error:e.message}}}
 if(m.type==='capture'){if(!web)throw Error('请在视频页截图');const tab=await chrome.tabs.get(sender.tab.id);if(!tab.active)throw Error('请回到视频标签页再截图');let data;await new Promise(r=>setTimeout(r,Math.max(0,600-(Date.now()-lastCapture))));lastCapture=Date.now();try{data=await chrome.tabs.captureVisibleTab(tab.windowId,{format:'png'})}catch{throw Error('请先点击浏览器插件图标，授予当前页截图权限')}const image=await createImageBitmap(await(await fetch(data)).blob()),r=m.rect;for(const k of ['x','y','width','height','vw','vh'])if(!Number.isFinite(r?.[k]))throw Error('画面边界无效');if(r.x<0||r.y<0||r.width<=0||r.height<=0||r.x+r.width>r.vw+1||r.y+r.height>r.vh+1)throw Error('请让完整视频画面出现在屏幕内再截图');const sx=image.width/r.vw,sy=image.height/r.vh,w=Math.round(r.width*sx),h=Math.round(r.height*sy),canvas=new OffscreenCanvas(w,h);canvas.getContext('2d').drawImage(image,r.x*sx,r.y*sy,r.width*sx,r.height*sy,0,0,w,h);const bytes=new Uint8Array(await(await canvas.convertToBlob({type:'image/png'})).arrayBuffer());let raw='';for(let j=0;j<bytes.length;j+=16384)raw+=String.fromCharCode(...bytes.subarray(j,j+16384));return {data:'data:image/png;base64,'+btoa(raw),width:w,height:h,screen:true}}
 throw Error('未知操作')
}
chrome.runtime.onMessage.addListener((m,sender,reply)=>{serialized(()=>handle(m,sender)).then(value=>reply({ok:true,value})).catch(e=>{lastError=e.message;reply({ok:false,error:e.message})});return true});
chrome.alarms.create('sync',{periodInMinutes:1});chrome.alarms.onAlarm.addListener(()=>serialized(syncQueue).catch(e=>lastError=e.message));
