(()=>{
 if(document.getElementById('guanying-extension'))return;const host=document.createElement('div');host.id='guanying-extension';const shadow=host.attachShadow({mode:'open'});document.body.append(host);const $=s=>shadow.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const css=':host{position:fixed;right:20px;top:90px;z-index:2147483647;font:14px "Microsoft YaHei",sans-serif;color:#eee5d6}*{box-sizing:border-box}section{width:360px;max-height:80vh;overflow:auto;background:#202027;border:1px solid #5d5662;border-radius:12px;padding:18px;box-shadow:0 8px 40px #0008}button{background:#fff12f;color:#5c2285;border:0;padding:9px;border-radius:6px;cursor:pointer;margin:4px 3px 4px 0}button:disabled{opacity:.5}input,textarea,select{display:block;width:100%;padding:8px;margin:5px 0 12px;background:#30303a;color:white;border:1px solid #555;border-radius:6px}input[type=checkbox]{display:inline;width:auto}label{display:block}textarea{min-height:75px}p,small{line-height:1.7;overflow-wrap:anywhere}.row{display:flex;gap:8px}.row>*{flex:1}img{max-width:100%}h3{margin:0 0 12px}#message{color:#ecd393}[hidden]{display:none!important}';
 let enabled=false,opened=false,start=null,shots=[],draft=null,busy=false,lastIdentity='',rangeText=[],rangeTimer=null;
 const msg=(type,input={})=>chrome.runtime.sendMessage({type,...input}).then(r=>{if(!r.ok)throw Error(r.error);return r.value}),video=()=>[...document.querySelectorAll('video')].find(v=>v.getBoundingClientRect().width>100&&!v.hidden),time=()=>{const v=video();if(!v||!Number.isFinite(v.currentTime))throw Error('请先让视频开始播放');return v.currentTime},notice=t=>{if($('#message'))$('#message').textContent=t};
 function identity(){const u=new URL(location.href),match=u.pathname.match(/\/video\/(BV[\w]+)|\/bangumi\/play\/(ep\d+)/);if(!match)throw Error('当前不是支持的视频页面');const part=u.searchParams.get('p')||'1',id='bilibili-'+(match[1]||match[2])+'-p'+part,url=u.origin+u.pathname+(part==='1'?'':'?p='+encodeURIComponent(part));return {id,url,title:document.querySelector('h1')?.getAttribute('title')||document.querySelector('h1')?.textContent?.trim()||document.title.replace(/_哔哩哔哩.*$/,'')}}
 function subtitle(){const v=video(),t=v?.currentTime||0;for(const track of Array.from(v?.textTracks||[])){if(track.mode==='disabled')continue;const cue=Array.from(track.activeCues||[])[0];if(cue)return {text:cue.text,start:cue.startTime,end:cue.endTime,exact:true}}const nodes=[...document.querySelectorAll('.bpx-player-subtitle-panel .bpx-player-subtitle-panel-text,.bpx-player-subtitle-panel .subtitle-item-text,.bilibili-player-video-subtitle .subtitle-item-text')].filter(n=>n.getBoundingClientRect().height>0);return {text:nodes.map(n=>n.textContent.trim()).filter(Boolean).join('\n'),start:Math.max(0,t-3),end:Math.min(v?.duration||t+3,t+3),exact:false}}
 async function capture(frame=false){const v=video();if(!v)throw Error('未找到视频播放器');const t=time();if(frame&&v.videoWidth&&v.videoHeight){try{const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);return {image:crypto.randomUUID()+'.png',time:t,text:'',data:c.toDataURL('image/png'),width:c.width,height:c.height,screen:false}}catch{}}
 const r=v.getBoundingClientRect();host.style.visibility='hidden';await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));try{const shot=await msg('capture',{rect:{x:r.x,y:r.y,width:r.width,height:r.height,vw:innerWidth,vh:innerHeight}});return {...shot,image:crypto.randomUUID()+'.png',time:t,text:subtitle().text}}finally{host.style.visibility='visible'}}
 async function run(fn){if(busy)return;busy=true;try{await fn()}catch(e){if(!opened)panel();notice(e.message)}finally{busy=false}}
 function panel(){opened=true;shadow.innerHTML=`<style>${css}</style><section><h3>观影 · 私人摘记 <button id="hide">收起 H</button></h3><p id="status">正在检查账号…</p><label><input type="checkbox" id="keys" ${enabled?'checked':''}> 启用快捷键（输入文字时自动停用）</label><div><button id="quote">摘一句 N</button><button id="shot">截图 S</button><button id="frame">收藏画面 B</button></div><div><button id="begin">片段起点 I</button><button id="end">片段终点 O</button></div><p id="message" role="status">在浏览器工具栏点击插件图标登录并授权截图。</p><button id="retry">重试同步</button><details><summary>新手指引</summary><p>默认地址用于同一台电脑，保持桌面观影运行。跨电脑使用同一个在线服务和账号。N 提取现有原字幕；取不到时填写原台词。I/O 记录片段，编辑时可加入多幅画面，回桌面导出两种长图。</p><p>网页截图按屏幕像素无损保存，面板会标明尺寸。B 优先尝试视频原尺寸；受跨域或保护限制时回退屏幕截图。不会下载或转码视频。</p></details><div id="editor"></div></section>`;
 $('#keys').onchange=e=>enabled=e.target.checked;$('#hide').onclick=hide;$('#quote').onclick=()=>run(()=>action('quote'));$('#shot').onclick=()=>run(()=>action('shot'));$('#frame').onclick=()=>run(()=>action('frame'));$('#begin').onclick=()=>run(()=>action('begin'));$('#end').onclick=()=>run(()=>action('end'));$('#retry').onclick=()=>run(async()=>{await msg('retry');await status()});status();if(draft)editor();
 }
 function hide(){opened=false;shadow.innerHTML=`<style>${css}</style><button id="show" title="展开观影摘记 H">影</button>`;$('#show').onclick=panel}
 async function status(){try{const s=await msg('status');if($('#status'))$('#status').textContent=(s.connected?(s.remote?'在线账号：':'本机账号：')+s.username:'请点击插件图标登录')+' · 待同步 '+s.pending+' 条';if(s.error)notice(s.error)}catch(e){notice(e.message)}}
 async function action(kind){const v=video();if(!v)throw Error('未找到正在播放的视频');const identityNow=identity();if(lastIdentity&&lastIdentity!==identityNow.id){start=null;rangeText=[];clearInterval(rangeTimer)}lastIdentity=identityNow.id;if(draft&&kind!=='begin')throw Error('请先保存或取消正在编辑的摘记');if(kind==='begin'){start=time();rangeText=[];clearInterval(rangeTimer);rangeTimer=setInterval(()=>{const text=subtitle().text;if(text&&rangeText.at(-1)!==text)rangeText.push(text)},500);notice('已标记起点 '+start.toFixed(2)+' 秒，播放到终点按 O');return}const t=time(),sub=subtitle();if(kind==='end'&&(start===null||t<=start))throw Error('请先按 I 标记起点，再播放到终点');v.pause();const shot=await capture(kind==='frame');shots=[shot];draft={id:crypto.randomUUID(),itemId:identityNow.id,episodeId:identityNow.id+'-episode',kind:kind==='end'?'quote':kind,start:kind==='end'?start:kind==='quote'?sub.start:t,end:kind==='end'?t:kind==='quote'?Math.max(sub.end,sub.start+.1):t,text:kind==='end'?rangeText.concat(sub.text&&rangeText.at(-1)!==sub.text?[sub.text]:[]).join('\n'):kind==='quote'?sub.text:'',comment:'',tags:'',color:'gold',created:new Date().toISOString(),updated:new Date().toISOString()};
 if(kind==='end'){start=null;clearInterval(rangeTimer)}if(!opened)panel();else editor();notice(kind==='quote'&&!sub.exact?'已保存当前画面；时间范围可微调，台词只取播放器原文，无字幕时请手填':'编辑摘记，保存后回到观影整理');
 }
 function editor(){if(!draft)return;$('#editor').innerHTML=`<hr><h3>${draft.kind==='quote'?'留住这段台词':'收藏画面'}</h3><div class="row"><label>开始（秒）<input id="start" type="number" step=".01" min="0" value="${draft.start.toFixed(2)}"></label><label>结束（秒）<input id="finish" type="number" step=".01" min="0" value="${draft.end.toFixed(2)}"></label></div><label>原台词<textarea id="text">${esc(draft.text)}</textarea></label><label>我的感想<textarea id="comment">${esc(draft.comment)}</textarea></label><label>标签<input id="tags" value="${esc(draft.tags)}"></label><label>归类<select id="kind"><option value="movie">电影</option><option value="series">剧集</option></select></label><div id="shots">${shots.map((s,i)=>`<div><img src="${s.data}"><small>${s.width}×${s.height} · ${s.screen?'屏幕截图':'视频原尺寸'} · ${s.time.toFixed(2)}秒</small><button data-remove="${i}">移除</button></div>`).join('')}</div><button id="append">加入当前画面</button><button id="save">保存 Ctrl+Enter</button><button id="cancel">取消</button>`;
 $('#kind').value=draft.filmKind||'movie';$('#append').onclick=()=>run(async()=>{if(shots.length>=20)throw Error('每条笔记最多 20 张');readEditor();shots.push(await capture());editor()});$('#cancel').onclick=()=>{draft=null;shots=[];$('#editor').innerHTML='';notice('已取消本条摘记')};shadow.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{readEditor();shots.splice(Number(b.dataset.remove),1);editor()});$('#save').onclick=()=>run(save);
 }
 function readEditor(){draft={...draft,start:Number($('#start').value),end:Number($('#finish').value),text:$('#text').value,comment:$('#comment').value,tags:$('#tags').value,filmKind:$('#kind').value}}
 async function save(){readEditor();if(draft.end<draft.start||draft.start<0||!Number.isFinite(draft.start)||!Number.isFinite(draft.end))throw Error('请检查片段起止时间');const info=identity();if(info.id!==draft.itemId)throw Error('视频已切换，请返回原视频保存这条摘记');const {filmKind,...note}=draft,item={id:info.id,source:'bilibili',title:info.title,kind:filmKind,status:'watching',rating:0,category:'B 站',review:'',sessions:[],added:Date.now(),lastPlayed:Date.now(),episodes:[{id:note.episodeId,title:info.title,path:info.url,position:video().currentTime,duration:Number.isFinite(video().duration)?video().duration:0,season:1,episode:1}]};const result=await msg('save',{item,note:{...note,shots,updated:new Date().toISOString()}});draft=null;shots=[];$('#editor').innerHTML='';await status();notice(result.synced?'已同步 · 在观影桌面版查看摘记':'已保存在浏览器，等待同步 · '+result.error);}
 document.addEventListener('keydown',e=>{const key=e.key.toLowerCase(),editing=e.composedPath().some(n=>['INPUT','TEXTAREA','SELECT'].includes(n.tagName)||n.isContentEditable);if(editing){if(e.ctrlKey&&key==='enter'&&draft){e.preventDefault();e.stopImmediatePropagation();run(save)}return}if(!enabled||e.ctrlKey||e.altKey||e.metaKey)return;if(key==='h'){e.preventDefault();e.stopImmediatePropagation();opened?hide():panel();return}const kind={n:'quote',s:'shot',b:'frame',i:'begin',o:'end'}[key];if(kind){e.preventDefault();e.stopImmediatePropagation();run(()=>action(kind))}},true);
 chrome.runtime.onMessage.addListener((m,sender,reply)=>{if(m.type==='toggle'){opened?hide():panel();reply({ok:true})}});
 document.addEventListener('fullscreenchange',()=>{(document.fullscreenElement||document.body).append(host)});
 let reviewTimer=null;function review(){const u=new URL(location.href),t=Number(u.searchParams.get('t')),end=Number(u.searchParams.get('gy_end'));if(!u.searchParams.has('t')||!Number.isFinite(t)||t<0)return;let tries=0;clearInterval(reviewTimer);reviewTimer=setInterval(()=>{const v=video();if(v?.readyState>=1&&v.duration>t){v.currentTime=t;clearInterval(reviewTimer);if(end>t&&end<=v.duration+.5){const ontime=()=>{if(v.currentTime>=end){if(u.searchParams.get('gy_loop')==='1')v.currentTime=t;else{v.pause();v.removeEventListener('timeupdate',ontime)}}};v.addEventListener('timeupdate',ontime)}notice('回看片段已定位')}else if(++tries>120)clearInterval(reviewTimer)},500)}
 hide();review();
})()

