const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');const {createService}=require('../src/account-service.cjs'),{AccountClient,cleanItem}=require('../src/account-client.cjs'),{Store}=require('../src/store.cjs');
const secure={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()};
test('账号隔离、双客户端同步、截图、冲突选择、删除和重启持久化',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'guanying-accounts-')),service=await createService(path.join(root,'service')),a=await Store.open(path.join(root,'a')),b=await Store.open(path.join(root,'b'));
 try{
 const ca=new AccountClient(a,secure,service.url),cb=new AccountClient(b,secure,service.url),login={url:service.url,username:'private.user',password:'strong-password-123'};
 await ca.login({...login,register:true});await cb.login(login);await assert.rejects(cb.login({...login,password:'wrong-password-123'}));a.import(['C:/Private/Test.mkv']);const item=a.list()[0],ep=item.episodes[0];assert.equal(cleanItem(item).episodes[0].path,'');assert(!JSON.stringify(cleanItem(item)).includes('C:/Private'));
 const name='test-frame.png',bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');fs.writeFileSync(path.join(a.root,'assets',name),bytes);a.saveNote({itemId:item.id,episodeId:ep.id,kind:'quote',start:1,end:3,text:'原文',shots:[{image:name,time:1,width:1,height:1}]});await ca.sync();await cb.sync();assert.equal(b.notes()[0].text,'原文');assert.equal(b.list()[0].episodes[0].path,'');assert(fs.readFileSync(path.join(b.root,'assets',name)).equals(bytes));assert.equal(a.list()[0].episodes[0].path,'C:/Private/Test.mkv');
 const n=a.notes()[0];a.saveNote({...n,text:'电脑 A'});b.saveNote({...n,text:'电脑 B'});await ca.sync();await cb.sync();assert.equal(cb.status().conflicts,1);assert.equal(b.notes()[0].text,'电脑 B');await cb.resolve('note:'+n.id,'remote');assert.equal(b.notes()[0].text,'电脑 A');b.saveNote({...b.notes()[0],text:'再改 B'});a.saveNote({...a.notes()[0],text:'再改 A'});await ca.sync();await cb.sync();await cb.resolve('note:'+n.id,'local');await ca.sync();assert.equal(a.notes()[0].text,'再改 B');
 a.saveNote({...a.notes()[0],text:'云端先改'});await ca.sync();const originalRequest=cb.request.bind(cb);let changed=false;cb.request=async(route,options)=>{if(route==='/records'&&!options?.method&&!changed){changed=true;b.saveNote({...b.notes()[0],text:'同步期间输入的文字'})}return originalRequest(route,options)};await cb.sync();assert.equal(b.notes()[0].text,'同步期间输入的文字');assert.equal(cb.status().conflicts,1);cb.request=originalRequest;await cb.resolve('note:'+n.id,'local');await ca.sync();assert.equal(a.notes()[0].text,'同步期间输入的文字');
 const other=await fetch(service.url+'/auth/register',{method:'POST',body:JSON.stringify({username:'another.user',password:'another-password-123'})}).then(r=>r.json());assert.equal((await fetch(service.url+'/records',{headers:{Authorization:'Bearer '+other.token}}).then(r=>r.json())).records.length,0);assert.equal((await fetch(service.url+'/assets/'+name,{headers:{Authorization:'Bearer '+other.token}})).status,404);
 const invalid=await ca.request('/records',{method:'POST',body:JSON.stringify({records:[{key:'item:broken',revision:0,value:{id:'broken',kind:'movie',title:'bad',added:1,episodes:[{id:'e',path:'C:/secret'}]}}]})}).then(()=>false,()=>true);assert(invalid);
 a.deleteNote(n.id);await ca.sync();await cb.sync();assert.equal(b.notes().length,0);await cb.logout();await assert.rejects(cb.login({url:service.url,username:'another.user',password:'another-password-123'}),/绑定/);await cb.login(login);await cb.sync();assert.equal(cb.status().connected,true);
 const reopened=new AccountClient(b,secure,service.url);assert.equal(reopened.status().connected,true);assert(reopened.status().lastSync);a.remove(item.id);await ca.sync();await reopened.sync();assert.equal(b.list().length,0);
 }finally{await service.close();a.db.close();b.db.close();}
});

