const {_electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),work=path.resolve(root,'../../work'),testRoot=path.join(work,'experience-'+Date.now());fs.mkdirSync(testRoot,{recursive:true});
const env={...process.env,GUANYING_DATA:path.join(testRoot,'data')};delete env.ELECTRON_RUN_AS_NODE;
const source=path.join(work,'test-film.avi'),hevc=path.join(work,'test-hevc.mkv'),e2=path.join(testRoot,'星光.S01E02.avi'),e10=path.join(testRoot,'星光.S01E10.avi'),subs=path.join(testRoot,'dialogue.srt');fs.copyFileSync(source,e2);fs.copyFileSync(source,e10);fs.appendFileSync(e10,'episode-ten');fs.writeFileSync(subs,'1\n00:00:01,000 --> 00:00:03,000\n第一句台词\nFirst sentence.\n\n2\n00:00:04,000 --> 00:00:06,000\n第二句台词\nSecond sentence.');
(async()=>{const app=await _electron.launch({executablePath:process.env.GUANYING_EXECUTABLE||process.env.GUANYING_RUNTIME,args:process.env.GUANYING_EXECUTABLE?[]:[root],env,timeout:30000});const p=await app.firstWindow(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{
await p.waitForSelector('#import');await p.evaluate(async files=>{await cinema.importPaths(files,{kind:'series',title:'星光剧集'});await refresh();render();},[e10,e2]);let data=await p.evaluate(()=>cinema.init());const series=data.items[0];assert.deepEqual(series.episodes.map(e=>e.episode),[2,10]);await p.click('[data-play]');await p.waitForFunction(()=>state.duration>10);await p.evaluate(()=>cinema.control('pause',true));await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},subs);await p.evaluate(async()=>{await cinema.loadSubtitles(current.id,episode.id);await refresh();});await p.evaluate(()=>cinema.control('seek',1.3));await p.waitForFunction(()=>state['sub-text']?.includes('第一句'));await p.click('#mark-start');await p.evaluate(()=>cinema.control('pause',false));await p.waitForFunction(()=>state['time-pos']>5);await p.click('#mark-end');await p.waitForSelector('#note-comment',{timeout:20000});assert.match(await p.inputValue('#note-text'),/第一句/);assert.match(await p.inputValue('#note-text'),/第二句/);await p.fill('#note-comment','起止快捷键完整片段');await p.click('#submit');await p.waitForSelector('#modal:not([open])',{state:'attached'});await p.click('[data-panel="notes"]');await p.click('[data-loop]');await p.waitForFunction(()=>state.reviewLoop&&state['time-pos']<2);await p.waitForFunction(()=>state['time-pos']>4);await p.waitForFunction(()=>state['time-pos']<2,{timeout:10000});await p.click('#review-exit');await p.evaluate(()=>cinema.control('pause',true));
await p.click('#tracks');await p.fill('#sub-delay','1.2');await p.click('#submit');await p.waitForSelector('#modal:not([open])',{state:'attached'});await p.click('[data-panel="episodes"]');await p.click(`[data-episode="${series.episodes[1].id}"]`);await p.waitForFunction(id=>state.active?.episodeId===id&&state.duration>10,series.episodes[1].id);await p.evaluate(()=>cinema.control('pause',true));await p.click(`[data-episode="${series.episodes[0].id}"]`);await p.waitForFunction(()=>Math.abs(state['sub-delay']-1.2)<.01);await p.click('#focus');await p.waitForFunction(()=>document.querySelector('.player-shell').classList.contains('focus-mode'));await p.keyboard.press('h');await p.waitForFunction(()=>!focusMode);
await p.click('#back');await p.evaluate(async file=>{await cinema.importPaths([file]);await refresh();render()},hevc);data=await p.evaluate(()=>cinema.init());const hd=data.items.find(i=>i.episodes[0].sourcePath===hevc);await p.click(`[data-play="${hd.id}"]`);await p.waitForFunction(()=>state['video-params']?.w===1920);await p.evaluate(()=>cinema.control('pause',true));assert((await p.evaluate(()=>state['track-list'])).some(t=>t.type==='audio'));await p.click('#shot');await p.waitForFunction(()=>data.notes.some(n=>n.kind==='shot'));const snap=(await p.evaluate(()=>cinema.listNotes())).find(n=>n.kind==='shot');assert.equal(snap.shots[0].width,1920);assert.equal(snap.shots[0].height,1080);await p.click('#back');
await app.evaluate(({dialog},folder)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:folder+'/backup.zip'})},testRoot);await p.evaluate(()=>cinema.backup());const originalNotes=await p.evaluate(()=>cinema.listNotes());await p.evaluate(id=>cinema.deleteNote(id),originalNotes[0].id);await app.evaluate(({dialog},folder)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder+'/backup.zip']});dialog.showMessageBox=async()=>({response:1})},testRoot);assert(await p.evaluate(()=>cinema.restore()));assert.equal((await p.evaluate(()=>cinema.listNotes())).length,originalNotes.length);assert(fs.readdirSync(path.join(testRoot,'data','backups')).some(n=>n.startsWith('before-restore')));
await app.evaluate(({dialog},folder)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:folder+'/notes.zip'})},testRoot);await p.evaluate(()=>cinema.exportMarkdown());assert(fs.statSync(path.join(testRoot,'notes.zip')).size>10000);
const replacement=path.join(testRoot,'relocated.avi');fs.renameSync(e2,replacement);await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},replacement);await p.evaluate(async ids=>{await cinema.relink(...ids);await refresh();render()},[series.id,series.episodes[0].id]);await p.click(`[data-play="${series.id}"]`);await p.waitForFunction(()=>state.duration>10);assert.equal((await p.evaluate(()=>cinema.listNotes())).length,originalNotes.length);await p.evaluate(()=>cinema.control('pause',true));await p.screenshot({path:path.join(testRoot,'experience.png')});assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,testRoot,checks:['series-natural-order','I-O-range','multi-subtitle-shots','loop-review','subtitle-offset-persist','episode-switch','focus-mode','HEVC-MKV-1080p-AAC','original-size-PNG','backup-restore-with-safety-backup','markdown-images','relink-keeping-notes']}));
}catch(e){await p.screenshot({path:path.join(testRoot,'failure.png')}).catch(()=>{});console.log('UI',await p.locator('#toast').textContent(),errors);throw e;}finally{await app.close();}})().catch(e=>{console.error(e);process.exitCode=1});
