const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{createService}=require('../src/account-service.cjs');
const root=path.resolve(__dirname,'..'),folder=path.resolve(root,'../../work/extension-'+Date.now());fs.mkdirSync(folder,{recursive:true});
(async()=>{const service=await createService(path.join(folder,'service')),testExtension=path.join(folder,'extension');fs.cpSync(path.join(root,'extension'),testExtension,{recursive:true});const manifest=JSON.parse(fs.readFileSync(path.join(testExtension,'manifest.json')));manifest.host_permissions.push('<all_urls>');fs.writeFileSync(path.join(testExtension,'manifest.json'),JSON.stringify(manifest));let context;try{context=await chromium.launchPersistentContext(path.join(folder,'browser'),{executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:false,args:['--disable-extensions-except='+testExtension,'--load-extension='+testExtension,'--no-first-run','--disable-features=msEdgeSidebarV2'],viewport:{width:1200,height:850}});const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker',{timeout:20000}),id=new URL(worker.url()).host;
 const popup=await context.newPage();await popup.goto('chrome-extension://'+id+'/popup.html');await popup.fill('#url',service.url);await popup.fill('#username','extension-user');await popup.fill('#password','test-password-123');await popup.check('#register');await popup.click('#submit');await popup.waitForFunction(()=>document.querySelector('#status').textContent.includes('已登录'));
 const page=await context.newPage();await page.route('https://www.bilibili.com/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><meta charset="UTF-8"><h1 title="B 站测试影片">B 站测试影片</h1><video style="width:640px;height:360px;background:linear-gradient(30deg,purple,yellow)" controls></video><div class="bpx-player-subtitle-panel"><span class="bpx-player-subtitle-panel-text">原台词 Exactly the original.</span></div>'}));await page.goto('https://www.bilibili.com/video/BV1Test12345/');await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=640;c.height=360;const x=c.getContext('2d'),stream=c.captureStream(25),rec=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8'}),chunks=[];rec.ondataavailable=e=>chunks.push(e.data);const timer=setInterval(()=>{x.fillStyle='#6633ee';x.fillRect(0,0,640,360);x.fillStyle='#fff12f';x.fillRect(50,50,200,150)},40);rec.start();await new Promise(r=>setTimeout(r,14000));await new Promise(r=>{rec.onstop=r;rec.stop()});clearInterval(timer);stream.getTracks().forEach(t=>t.stop());const v=document.querySelector('video');v.src=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));await new Promise(r=>v.onloadedmetadata=r);v.currentTime=5;await new Promise(r=>v.onseeked=r)});await page.waitForSelector('#guanying-extension');await page.locator('#guanying-extension').locator('#show').click();await page.locator('#guanying-extension').locator('#status').waitFor();
 // Activate the toolbar action using its browser shortcut to grant activeTab.
 await page.evaluate(async id=>{const host=document.getElementById('guanying-extension');host.setAttribute('data-test','ready')},id);
 await page.bringToFront();
 await page.locator('#guanying-extension').locator('#quote').click();await page.locator('#guanying-extension').locator('#text').waitFor();assert.equal(await page.locator('#guanying-extension').locator('#text').inputValue(),'原台词 Exactly the original.');await page.locator('#guanying-extension').locator('#comment').fill('B 站摘记测试');await page.locator('#guanying-extension').locator('#save').click();await page.waitForFunction(()=>document.getElementById('guanying-extension').shadowRoot.querySelector('#message').textContent.includes('已同步'));
 const records=await worker.evaluate(async()=>{const c=(await chrome.storage.local.get('config')).config;return (await fetch(c.url+'/records',{headers:{Authorization:'Bearer '+c.token}}).then(r=>r.json())).records});assert.equal(records.length,2);const n=records.find(r=>r.key.startsWith('note:')).value;assert.equal(n.comment,'B 站摘记测试');assert(Math.abs(n.start-2)<.1);assert(Math.abs(n.end-8)<.1);assert.equal(n.shots[0].width,640);assert(!('data'in n.shots[0]));await page.locator('#guanying-extension').locator('#keys').check();await page.evaluate(()=>document.getElementById('guanying-extension').shadowRoot.activeElement?.blur());await page.keyboard.press('i');await page.evaluate(async()=>{const v=document.querySelector('video');v.currentTime=11;await new Promise(r=>v.onseeked=r)});await page.keyboard.press('o');await page.locator('#guanying-extension').locator('#text').waitFor();assert.equal(await page.locator('#guanying-extension').locator('#start').inputValue(),'5.00');assert.equal(await page.locator('#guanying-extension').locator('#finish').inputValue(),'11.00');await page.locator('#guanying-extension').locator('#cancel').click();
 await service.close();await page.locator('#guanying-extension').locator('#shot').click();await page.locator('#guanying-extension').locator('#save').waitFor();await page.locator('#guanying-extension').locator('#save').click();await page.waitForFunction(()=>document.getElementById('guanying-extension').shadowRoot.querySelector('#message').textContent.includes('等待同步'));assert.equal(await worker.evaluate(async()=>(await chrome.storage.local.get('queue')).queue.length),1);await page.screenshot({path:path.join(folder,'plugin.png')});console.log(JSON.stringify({ok:true,folder,checks:['real-edge-unpacked-load','login','fixture-original-subtitle','screenshot-crop','note-upload','IO-keyboard','offline-persisted-queue'],capture:'real browser capture using isolated test-only all_urls permission; production activeTab toolbar activation needs manual check; no real Bilibili playback verified'}));
 }catch(e){if(context){for(const p of context.pages()){if(p.url().includes('bilibili.com/video'))console.log('plugin error',await p.evaluate(()=>document.getElementById('guanying-extension')?.shadowRoot.querySelector('#message')?.textContent));}}throw e}finally{await context?.close();await service.close()}})().catch(e=>{console.error(e);process.exitCode=1});
