const {_electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),work=path.resolve(root,'../../work'),testRoot=path.join(work,'import-'+Date.now());fs.mkdirSync(testRoot,{recursive:true});
const env={...process.env,GUANYING_DATA:path.join(testRoot,'data')};delete env.ELECTRON_RUN_AS_NODE;
const movie=path.join(testRoot,'拖入测试电影.avi'),other=path.join(testRoot,'选择资源电影.avi');fs.copyFileSync(path.join(work,'test-film.avi'),movie);fs.copyFileSync(movie,other);fs.appendFileSync(other,'different-copy');
const digest=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
async function launch(){return _electron.launch({executablePath:process.env.GUANYING_EXECUTABLE||process.env.GUANYING_RUNTIME,args:process.env.GUANYING_EXECUTABLE?[]:[root],env,timeout:30000})}
(async()=>{let app=await launch(),p=await app.firstWindow(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{
await p.waitForSelector('#import');await p.click('#import');await p.waitForSelector('#import-drop');assert(await p.locator('#import-kind').isVisible());await p.selectOption('#import-kind','movie');await p.fill('#import-category','科幻、喜剧');await p.screenshot({path:path.join(testRoot,'drop-dialog.png')});
// CDP drag data contains a real filesystem file; exercises DataTransfer -> preload -> actual copying.
const client=await app.context().newCDPSession(p),box=await p.locator('#import-drop').boundingBox();const drag={items:[],files:[movie],dragOperationsMask:1};const x=box.x+box.width/2,y=box.y+box.height/2;
await client.send('Input.dispatchDragEvent',{type:'dragEnter',x,y,data:drag});await client.send('Input.dispatchDragEvent',{type:'dragOver',x,y,data:drag});await client.send('Input.dispatchDragEvent',{type:'drop',x,y,data:drag});
await p.waitForFunction(()=>importState.files.some(f=>f.status==='done')&&!importState.running,null,{timeout:30000});let data=await p.evaluate(()=>cinema.init());assert.equal(data.items.length,1);const saved=data.items[0];assert.equal(saved.kind,'movie');assert.equal(saved.category,'科幻、喜剧');const ep=saved.episodes[0];assert(ep.verified);assert.notEqual(ep.path,movie);assert.equal(digest(ep.path),digest(movie));assert.match(await p.locator('#import-summary').textContent(),/已保存并校验/);await p.screenshot({path:path.join(testRoot,'saved.png')});
await p.evaluate(file=>startImport([file]),movie);await p.waitForSelector('#dup-skip');await p.click('#dup-skip');assert.equal((await p.evaluate(()=>cinema.init())).items.length,1);await p.evaluate(()=>importDialog());
await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},other);await p.click('#pick-files');await p.waitForFunction(()=>data.items.length===2&&!importState.running);assert.equal((await p.evaluate(()=>cinema.init())).items.length,2);await p.click('#import-done');await p.evaluate(async id=>{const i=(await cinema.init()).items.find(i=>i.id!==id);await cinema.removeItem(i.id);await refresh();render()},saved.id);await p.click('[data-view="resources"]');await p.waitForSelector('[data-resource-add]');await p.click('[data-resource-add]');await p.waitForSelector('[data-resource-detail]');await p.evaluate(async()=>{await refresh();view='library';render()});fs.unlinkSync(movie);fs.unlinkSync(other);
await p.click(`[data-play="${saved.id}"]`);await p.waitForFunction(()=>state.duration>10&&state['time-pos']>0);await p.evaluate(()=>cinema.control('pause',true));await p.click('#frame');await p.waitForFunction(()=>data.notes.length===1);assert.equal((await p.evaluate(()=>cinema.init())).notes.length,1);await p.click('#back');await p.click('[data-view="settings"]');assert.match(await p.locator('.main').textContent(),/已保存 2 个视频/);assert.match(await p.locator('.main').textContent(),/本机服务不支持换机/);await p.screenshot({path:path.join(testRoot,'storage.png')});
await app.close();app=await launch();p=await app.firstWindow();p.on('pageerror',e=>errors.push(e.message));await p.waitForSelector(`[data-play="${saved.id}"]`);await p.click(`[data-play="${saved.id}"]`);await p.waitForFunction(()=>state.duration>10);assert.equal((await p.evaluate(()=>cinema.init())).notes.length,1);assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,testRoot,checks:['actual-import-button','native-file-picker','real-file-drag-into-dialog','copy-progress','SHA256-equality','delete-source-then-play','app-restart-with-source-gone','notes-retained','storage-location','explicit-not-cloud-label']}));
}catch(e){await p.screenshot({path:path.join(testRoot,'failure.png')}).catch(()=>{});console.log('UI',await p.locator('#toast').textContent(),errors);throw e;}finally{await app.close();}})().catch(e=>{console.error(e);process.exitCode=1});
