const batchSelections=new Map,batchAnchors=new Map;let resourceRows=[];
const batchSet=scope=>{if(!batchSelections.has(scope))batchSelections.set(scope,new Set);return batchSelections.get(scope)};
function batchCheckbox(scope,id,label){return `<label class="batch-check" title="${esc(label)}"><input type="checkbox" data-batch-scope="${scope}" data-batch-id="${esc(id)}" aria-label="${esc(label)}" ${batchSet(scope).has(id)?'checked':''}>选择</label>`}
function mountBatch(scope,container,ids){const target=$(container);if(!target)return;const unique=[...new Set(ids)],set=batchSet(scope);for(const id of [...set])if(!unique.includes(id))set.delete(id);let bar=$('[data-batch-bar="'+scope+'"]');if(!bar){bar=document.createElement('div');bar.className='batch-bar';bar.dataset.batchBar=scope;target.before(bar)}bar._batchIds=unique;bar._batchContainer=container;bindBatchChecks(scope);paintBatchBar(scope);}
function bindBatchChecks(scope){const boxes=$$('[data-batch-scope="'+scope+'"]');for(const box of boxes){box.checked=batchSet(scope).has(box.dataset.batchId);box.closest('article,.episode')?.classList.toggle('batch-selected',box.checked);box.onclick=e=>{e.stopPropagation();const bar=$('[data-batch-bar="'+scope+'"]'),ids=bar?._batchIds||boxes.map(x=>x.dataset.batchId),id=box.dataset.batchId,set=batchSet(scope),anchor=batchAnchors.get(scope);if(e.shiftKey&&ids.includes(anchor)){const a=ids.indexOf(anchor),b=ids.indexOf(id);for(const v of ids.slice(Math.min(a,b),Math.max(a,b)+1))box.checked?set.add(v):set.delete(v)}else box.checked?set.add(id):set.delete(id);batchAnchors.set(scope,id);bindBatchChecks(scope);paintBatchBar(scope)};box.closest('label').onclick=e=>e.stopPropagation();}}
function paintBatchBar(scope){const bar=$('[data-batch-bar="'+scope+'"]');if(!bar)return;const ids=bar._batchIds||[],count=batchSet(scope).size,isNotes=scope==='notes',isResources=scope==='resources',isEpisodes=scope==='episodes';bar.innerHTML=`<div class="row wrap"><label><input type="checkbox" data-batch-all ${count&&count===ids.length?'checked':''}>全选当前列表</label><b>已选 ${count} / ${ids.length} ${isNotes?'条摘记':isEpisodes||isResources?'个资源':'部影片'}</b><button class="small" data-batch-clear>取消选择</button></div><div class="row wrap">${isNotes?'<button data-batch-edit>批量标签 / 颜色</button>':'<button data-batch-edit>批量修改档案</button>'}<button data-batch-export>导出所选摘记</button>${isResources?'<button data-batch-add>未入库副本加入片库</button><button data-batch-trash class="danger">清理未入库副本</button>':''}<button data-batch-remove class="danger">${isNotes?'删除摘记':isEpisodes?'移除选中集数':isResources?'移出选中资源':'移出片库'}</button></div>`;bar.querySelector('[data-batch-all]').indeterminate=count>0&&count<ids.length;bar.querySelector('[data-batch-all]').onchange=e=>{const set=batchSet(scope);for(const id of ids)e.target.checked?set.add(id):set.delete(id);bindBatchChecks(scope);paintBatchBar(scope)};bar.querySelector('[data-batch-clear]').onclick=()=>{batchSet(scope).clear();bindBatchChecks(scope);paintBatchBar(scope)};
 for(const b of bar.querySelectorAll('button:not([data-batch-clear])'))b.disabled=!count;
 bar.querySelector('[data-batch-edit]').onclick=()=>safe(()=>isNotes?batchNotesDialog(scope):batchFilmsDialog(scope));bar.querySelector('[data-batch-export]').onclick=()=>safe(()=>batchExport(scope));bar.querySelector('[data-batch-remove]').onclick=()=>safe(()=>batchRemoveDialog(scope));if(isResources){bar.querySelector('[data-batch-add]').onclick=()=>safe(()=>batchAddResources());bar.querySelector('[data-batch-trash]').onclick=()=>safe(()=>batchTrashDialog())}}
function selectedResourceRows(){return resourceRows.filter(e=>batchSet('resources').has(e.batchId))}
function selectedFilmIds(scope){const chosen=[...batchSet(scope)];if(scope==='resources')return [...new Set(selectedResourceRows().map(e=>e.itemId).filter(Boolean))];if(scope==='episodes')return data.items.filter(i=>i.episodes.some(e=>chosen.includes(e.id))).map(i=>i.id);return chosen}
async function batchFinish(scope,result){batchSet(scope).clear();await refresh();if(view==='player'&&(!current||!episode)){view='library';current=episode=null;await api.fullscreen(false)}render();const failed=result?.failed||[];toast(failed.length?`已完成部分操作，${failed.length} 个视频副本未能移入回收站，仍保留在原位置`:result?.sharedRetained?`操作完成；${result.sharedRetained} 份共用副本仍保留`:'批量操作已完成');if(failed.length)dialog(`<h2>这些副本仍保留</h2><p>片库记录已按选择处理。下面的文件未能移入回收站，可以稍后在全部资源重试。</p><p class="error">${failed.map(f=>esc(f.path)+' · '+esc(f.error)).join('<br>')}</p><div class="buttons"><button id="cancel">关闭</button></div>`)}
function batchFilmsDialog(scope){const ids=selectedFilmIds(scope);if(!ids.length)return toast('请选择已有影片档案的资源；未入库副本可先加入片库');formDialog('批量修改 '+ids.length+' 部影片',`<p>只修改填写的项目，其他内容保留。剧集仍保留各集及笔记。</p><label>电影 / 电视剧<select id="batch-kind"><option value="">不修改</option><option value="movie">电影</option><option value="series">电视剧</option></select></label><label>观看状态<select id="batch-status"><option value="">不修改</option><option value="want">想看</option><option value="watching">观看中</option><option value="done">已看</option></select></label><label>评分<select id="batch-rating"><option value="">不修改</option>${[0,1,2,3,4,5].map(n=>'<option value="'+n+'">'+(n?'★'.repeat(n):'清除评分')+'</option>').join('')}</select></label><label class="check"><input type="checkbox" id="batch-category-enabled">统一修改分类 / 标签（覆盖原分类）</label><input id="batch-category" placeholder="勾选后填写；留空会清除分类">`,async()=>{const patch={};for(const key of ['kind','status','rating']){const value=$('#batch-'+key).value;if(value!=='')patch[key]=key==='rating'?Number(value):value}if($('#batch-category-enabled').checked)patch.category=$('#batch-category').value;const result=await api.batchUpdateFilms(ids,patch);closeDialog();await batchFinish(scope,result)})}
function batchNotesDialog(scope){const ids=[...batchSet(scope)];formDialog('批量修改 '+ids.length+' 条摘记',`<label class="check"><input id="batch-tags-enabled" type="checkbox">统一修改标签（覆盖原标签）</label><input id="batch-tags" placeholder="留空并勾选可清除标签"><label>标记颜色<select id="batch-color"><option value="">不修改</option><option value="gold">暖金</option><option value="purple">淡紫</option><option value="green">灰绿</option></select></label>`,async()=>{const patch={};if($('#batch-tags-enabled').checked)patch.tags=$('#batch-tags').value;if($('#batch-color').value)patch.color=$('#batch-color').value;if(!Object.keys(patch).length)throw Error('请选择要修改的内容');const result=await api.batchUpdateNotes(ids,patch);closeDialog();await batchFinish(scope,result)})}
async function batchExport(scope){const ids=[...batchSet(scope)],selection=scope==='notes'?{noteIds:ids}:scope==='episodes'?{episodeIds:ids}:scope==='resources'?{episodeIds:selectedResourceRows().filter(e=>!e.orphan).map(e=>e.id)}:{itemIds:ids};if(await api.batchExport(selection))toast('所选摘记及原尺寸图片已导出')}
function batchRemoveDialog(scope){const isNotes=scope==='notes',isEp=scope==='episodes',isRes=scope==='resources',ids=[...batchSet(scope)],rows=isRes?selectedResourceRows():[],linked=rows.filter(e=>!e.orphan),actual=isRes?linked.map(e=>e.id):ids;if(!actual.length)return toast('选中的资源尚未入库；可使用“清理未入库副本”');const titles=isNotes?data.notes.filter(n=>ids.includes(n.id)).map(n=>n.text||data.items.find(i=>i.id===n.itemId)?.title||'画面摘记'):isRes?linked.map(e=>e.title):isEp?current.episodes.filter(e=>ids.includes(e.id)).map(e=>e.title):data.items.filter(i=>ids.includes(i.id)).map(i=>i.title);
 dialog(`<h2>${isNotes?'删除选中摘记':isEp||isRes?'移除选中资源':'移出片库'}</h2><p>处理 ${actual.length} ${isNotes?'条摘记':isEp||isRes?'个资源':'部影片'}：${titles.slice(0,8).map(esc).join('、')}${titles.length>8?'…':''}</p>${isNotes?'':`<label class="check"><input type="checkbox" id="batch-delete-media">同时将观影保存的视频副本移入回收站</label><p class="notice">默认保留视频。移除的影片 / 集数及其摘记和观影记录会先自动备份；剧集中未选的集数、共用副本和原下载文件保留。${isRes&&rows.some(e=>e.orphan)?'未入库副本不参加本次移出，可单独清理。':''}</p>`}<p>${isNotes?'操作前自动备份；电影、其他摘记及原图文件保留。':''}</p><div class="buttons"><button id="cancel">取消</button><button id="batch-confirm" class="danger">确认批量${isNotes?'删除':'移除'}</button></div>`);
 on('#batch-confirm',async()=>{$('#batch-confirm').disabled=true;try{const result=isNotes?await api.batchDeleteNotes(actual):isEp||isRes?await api.batchRemoveEpisodes(actual,$('#batch-delete-media').checked):await api.batchRemoveFilms(actual,$('#batch-delete-media').checked);closeDialog();await batchFinish(scope,result)}finally{if($('#batch-confirm'))$('#batch-confirm').disabled=false}});
}
async function batchAddResources(){const rows=selectedResourceRows().filter(e=>e.orphan);if(!rows.length)return toast('请选择未入库的影库副本');const result=await api.importPaths(rows.map(e=>e.path));await batchFinish('resources',result)}
function batchTrashDialog(){const rows=selectedResourceRows().filter(e=>e.orphan&&e.mediaFile);if(!rows.length)return toast('请选择没有片库引用的影库副本');dialog(`<h2>清理 ${rows.length} 个未入库副本</h2><p>${rows.slice(0,8).map(e=>esc(e.title)).join('、')}</p><p class="notice">只将未入库的影库副本移入回收站。仍有片库引用的资源、本机来源文件、截图和笔记不会删除。</p><div class="buttons"><button id="cancel">取消</button><button id="batch-trash-confirm" class="danger">确认移入回收站</button></div>`);on('#batch-trash-confirm',async()=>{$('#batch-trash-confirm').disabled=true;try{const result=await api.batchTrashResources(rows.map(e=>e.path));closeDialog();await batchFinish('resources',result)}finally{if($('#batch-trash-confirm'))$('#batch-trash-confirm').disabled=false}})}
document.addEventListener('keydown',e=>{if($('#modal').open||((e.target.tagName==='INPUT'&&e.target.type!=='checkbox')||['TEXTAREA','SELECT'].includes(e.target.tagName))||e.target.isContentEditable)return;const bars=$$('[data-batch-bar]');if(!bars.length)return;const bar=bars.find(b=>b._batchIds.length);if(!bar)return;const scope=bar.dataset.batchBar;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();for(const id of bar._batchIds)batchSet(scope).add(id);bindBatchChecks(scope);paintBatchBar(scope)}else if(e.key==='Escape'&&batchSet(scope).size){e.preventDefault();e.stopImmediatePropagation();batchSet(scope).clear();bindBatchChecks(scope);paintBatchBar(scope)}});

