const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const assetName=s=>typeof s==='string'&&/^[-\w]{1,100}\.(png|jpg|jpeg|webp)$/i.test(s);
function createService(root,{setupCode='',host='127.0.0.1',port=0}={}){
 fs.mkdirSync(root,{recursive:true});const file=path.join(root,'accounts.json');let db=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):{users:[],sessions:{},records:{}};const attempts=new Map;
 const flush=()=>{fs.writeFileSync(file+'.tmp',JSON.stringify(db));fs.renameSync(file+'.tmp',file)};
 const fail=(message,status=400)=>{throw Object.assign(Error(message),{status})};
 const server=http.createServer(async(req,res)=>{const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))};try{
  const origin=req.headers.origin;if(origin&&!/^chrome-extension:\/\/[a-p]+$/.test(origin)&&!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin))fail('来源未授权',403);
  if(origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin')};res.setHeader('Access-Control-Allow-Headers','Authorization,Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,OPTIONS');if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}
  const url=new URL(req.url,'http://localhost'),route=url.pathname;
  if(route==='/health'&&req.method==='GET')return send(200,{app:'guanying-account',version:1,localOnly:host==='127.0.0.1'});
  let body=Buffer.alloc(0);if(['POST','PUT'].includes(req.method)){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>24*1024*1024)fail('请求过大',413);chunks.push(chunk)}body=Buffer.concat(chunks)}
  const json=()=>{try{return JSON.parse(body.toString('utf8'))}catch{fail('请求格式错误')}};
  if(['/auth/register','/auth/login'].includes(route)&&req.method==='POST'){
   const input=json(),username=String(input.username||'').trim().toLowerCase(),password=String(input.password||'');if(!/^[a-z0-9_.@+-]{3,100}$/.test(username)||password.length<10||password.length>200)fail('账号使用 3–100 位英文、数字或邮箱；密码至少 10 位');
   const key=req.socket.remoteAddress+':'+username,bucket=attempts.get(key)||{count:0,time:Date.now()};if(Date.now()-bucket.time>600000){bucket.count=0;bucket.time=Date.now()}if(++bucket.count>12)fail('尝试过多，请十分钟后重试',429);attempts.set(key,bucket);
   let user=db.users.find(u=>u.username===username);
   if(route.endsWith('register')){if(setupCode&&input.setupCode!==setupCode)fail('注册邀请码不正确',403);if(host!=='127.0.0.1'&&!setupCode)fail('公开服务必须设置注册邀请码',403);if(user)fail('账号已存在',409);const salt=crypto.randomBytes(16).toString('hex');const derived=await new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(e,k)=>e?reject(e):resolve(k)));if(db.users.some(u=>u.username===username))fail('账号已存在',409);user={id:crypto.randomUUID(),username,salt,password:derived.toString('hex')};db.users.push(user);db.records[user.id]={};
   }else{const derived=await new Promise((resolve,reject)=>crypto.scrypt(password,user?.salt||'missing-user',64,(e,k)=>e?reject(e):resolve(k)));if(!user||!crypto.timingSafeEqual(derived,Buffer.from(user.password,'hex')))fail('账号或密码不正确',401)}
   const token=crypto.randomBytes(32).toString('hex');db.sessions[hash(token)]={userId:user.id,expires:Date.now()+30*86400000};flush();return send(200,{token,user:{id:user.id,username:user.username}});
  }
  const token=(req.headers.authorization||'').replace(/^Bearer /,''),session=db.sessions[hash(token)];if(!session||session.expires<Date.now())fail('请重新登录',401);const user=db.users.find(u=>u.id===session.userId);if(!user)fail('账号无效',401);
  if(route==='/auth/logout'&&req.method==='POST'){delete db.sessions[hash(token)];flush();return send(200,{ok:true})}
  if(route==='/records'&&req.method==='GET')return send(200,{records:Object.values(db.records[user.id]||{})});
  if(route==='/records'&&req.method==='POST'){const {records}=json();if(!Array.isArray(records)||records.length>500)fail('每批最多 500 条记录');if(new Set(records.map(r=>r?.key)).size!==records.length)fail('批次存在重复标识');for(const r of records){if(!r||JSON.stringify(r.value||{}).length>250000)fail('记录无效');if(!/^(item|note):[-\w]{1,100}$/.test(r.key)||!Number.isInteger(r.revision||0)||(r.revision||0)<0||(!r.deleted&&r.value?.id!==r.key.split(':')[1]))fail('记录标识无效');if(!r.deleted&&r.key.startsWith('item:')&&(typeof r.value.title!=='string'||!['movie','series'].includes(r.value.kind)||!Number.isFinite(r.value.added)||!Array.isArray(r.value.episodes)||!r.value.episodes.length||r.value.episodes.some(e=>!e.id||typeof e.path!=='string'||(e.path&&!/^https?:\/\//.test(e.path)))))fail('影片档案无效');if(!r.deleted&&r.key.startsWith('note:')&&(!r.value.itemId||!r.value.episodeId||typeof r.value.created!=='string'||!Number.isFinite(r.value.start)||!Number.isFinite(r.value.end)||!Array.isArray(r.value.shots)||r.value.shots.length>20||r.value.shots.some(s=>!assetName(s.image)||!Number.isFinite(s.time))||r.value.end<r.value.start||r.value.start<0||!['quote','shot','frame'].includes(r.value.kind)))fail('笔记内容无效');}const accepted=[],conflicts=[],target=db.records[user.id];for(const r of records){if(!/^(item|note):[-\w]{1,100}$/.test(r.key)||JSON.stringify(r.value||{}).length>250000)fail('记录无效');if(r.key.startsWith('item:')&&!r.deleted&&(!r.value?.id||!Array.isArray(r.value?.episodes)))fail('影片档案无效');if(r.key.startsWith('note:')&&!r.deleted&&(!r.value?.id||!r.value?.itemId||!Number.isFinite(r.value.start)||!Number.isFinite(r.value.end)))fail('笔记无效');const prev=target[r.key];if((prev?.revision||0)!==(r.revision||0)){conflicts.push({local:r,remote:prev});continue}const next={key:r.key,revision:(prev?.revision||0)+1,deleted:!!r.deleted,value:r.deleted?null:r.value,updated:new Date().toISOString()};target[r.key]=next;accepted.push(next)}flush();return send(200,{accepted,conflicts})}
  if(route.startsWith('/assets/')){const name=route.slice(8);if(!assetName(name))fail('图片名称无效');const dir=path.join(root,'assets',user.id),dest=path.join(dir,name);if(req.method==='PUT'){const png=body.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),jpg=body[0]===255&&body[1]===216,webp=body.subarray(0,4).toString()==='RIFF'&&body.subarray(8,12).toString()==='WEBP';if(!png&&!jpg&&!webp)fail('只接受有效图片');fs.mkdirSync(dir,{recursive:true});let used=0;for(const n of fs.readdirSync(dir))used+=fs.statSync(path.join(dir,n)).size;if(used+(fs.existsSync(dest)?0:body.length)>1024*1024*1024)fail('图片存储已达 1 GB，请扩容',413);if(fs.existsSync(dest)&&hash(fs.readFileSync(dest))!==hash(body))fail('同名图片内容不一致',409);fs.writeFileSync(dest+'.tmp',body);fs.renameSync(dest+'.tmp',dest);return send(200,{ok:true})}if(req.method==='GET'){if(!fs.existsSync(dest))fail('图片不存在',404);res.writeHead(200,{'Content-Type':pngType(name),'Cache-Control':'private,max-age=3600'});return fs.createReadStream(dest).pipe(res)}}
  fail('接口不存在',404);
 }catch(e){if(!res.headersSent)send(e.status||500,{error:e.status?e.message:'服务暂时不可用'});else res.end()}});
 return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,host,()=>resolve({server,url:'http://'+host+':'+server.address().port,close:()=>new Promise(r=>server.close(r))}))});
}
function pngType(name){return /\.jpe?g$/i.test(name)?'image/jpeg':/\.webp$/i.test(name)?'image/webp':'image/png'}
if(require.main===module)createService(process.env.GUANYING_ACCOUNT_DATA||path.join(process.cwd(),'account-data'),{host:process.env.HOST||'127.0.0.1',port:Number(process.env.PORT)||48721,setupCode:process.env.GUANYING_SETUP_CODE||''}).then(s=>console.log('Account service listening: '+s.url)).catch(e=>{console.error(e.message);process.exitCode=1});
module.exports={createService,assetName};
