const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const {assetName}=require('./account-service.cjs');
const digest=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
function cleanItem(item){return {...item,episodes:item.episodes.map(e=>{const {path:local,sourcePath,mediaFile,subtitle,cues,...rest}=e;return {...rest,path:/^https?:/.test(local)?local:'',availableLocally:false}})}}
class AccountClient{
 constructor(store,secure,localUrl){this.store=store;this.secure=secure;this.localUrl=localUrl;this.file=path.join(store.root,'account-client.json');this.config=fs.existsSync(this.file)?JSON.parse(fs.readFileSync(this.file,'utf8')):{};this.running=false;}
 persist(){fs.writeFileSync(this.file+'.tmp',JSON.stringify(this.config));fs.renameSync(this.file+'.tmp',this.file)}
 token(){return this.config.token?this.secure.decryptString(Buffer.from(this.config.token,'base64')):''}
 status(){return {username:this.config.username||'',url:this.config.url||this.localUrl,connected:!!this.config.token,remote:!!this.config.url&&!/^http:\/\/(127\.0\.0\.1|localhost)(:|\/|$)/.test(this.config.url),lastSync:this.config.lastSync||'',error:this.lastError||'',running:this.running,conflicts:this.config.conflicts?.length||0}}
 async request(route,options={}){const r=await fetch(this.config.url+route,{...options,headers:{Authorization:'Bearer '+this.token(),...(options.headers||{})},signal:AbortSignal.timeout(30000)}).catch(()=>{throw Error('服务连接失败，请检查网络；本机联动需保持观影运行')});if(!r.ok){let msg;try{msg=(await r.json()).error}catch{}throw Error(msg||'账号服务连接失败')}return r}
 async login({url,username,password,register=false,setupCode='',migrate=false}){if(this.running)throw Error('同步正在进行，请等待结束再登录或更换服务');if(!this.secure.isEncryptionAvailable())throw Error('Windows 安全凭据存储不可用');const u=new URL(url||this.localUrl);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['127.0.0.1','localhost'].includes(u.hostname)))throw Error('云端服务必须使用 HTTPS');const endpoint=u.origin+u.pathname.replace(/\/$/,'');const r=await fetch(endpoint+'/auth/'+(register?'register':'login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password,setupCode}),signal:AbortSignal.timeout(15000)});const body=await r.json();if(!r.ok)throw Error(body.error||'登录失败');if(this.config.userId&&(this.config.userId!==body.user.id||this.config.url!==endpoint)&&!migrate)throw Error('这份本机日记已绑定另一账号或服务。请使用原账号，避免把私人笔记混入其他账号');const same=this.config.userId===body.user.id&&this.config.url===endpoint;this.config={...(same?this.config:{}),url:endpoint,username:body.user.username,userId:body.user.id,token:this.secure.encryptString(body.token).toString('base64'),known:same?this.config.known||{}:{},conflicts:same?this.config.conflicts||[]:[]};this.persist();return this.status()}
 async logout(){if(this.running)throw Error('同步正在进行，请稍后退出');try{await this.request('/auth/logout',{method:'POST'})}catch{}this.config.token='';this.persist();return this.status()}
 async resolve(key,choice){if(this.running)throw Error('请等待同步结束');const c=(this.config.conflicts||[]).find(c=>c.local.key===key);if(!c)throw Error('冲突已处理');if(choice==='local'){this.config.known[key]={revision:c.remote?.revision||0,hash:'',deleted:false}}else if(choice==='remote'){if(!c.remote){const id=key.split(':')[1];if(key.startsWith('item:'))this.store.remove(id);else this.store.deleteNote(id);delete this.config.known[key]}else this.config.known[key]={revision:0,hash:c.local.deleted?'':digest(c.local.value),deleted:!!c.local.deleted}}else throw Error('请选择保留哪一版');this.config.conflicts=this.config.conflicts.filter(c=>c.local.key!==key);this.persist();return this.sync()}
 async sync(){if(!this.config.token)throw Error('请先登录');if(this.running)return this.status();this.running=true;try{
  const known=this.config.known||{},local=new Map;for(const item of this.store.list())local.set('item:'+item.id,cleanItem(item));for(const n of this.store.notes())local.set('note:'+n.id,n);
  const pending=[];for(const [key,value]of local)if(known[key]?.hash!==digest(value))pending.push({key,revision:known[key]?.revision||0,value});for(const [key,k]of Object.entries(known))if(!local.has(key)&&!k.deleted)pending.push({key,revision:k.revision,deleted:true});
  const images=new Set(pending.flatMap(r=>[...(r.value?.shots||[]).map(s=>s.image),r.value?.poster].filter(Boolean)));for(const r of pending)for(const shot of r.value?.shots||[])images.add(shot.image);for(const name of images){if(!assetName(name))continue;const file=path.join(this.store.root,'assets',name);if(fs.existsSync(file))await this.request('/assets/'+name,{method:'PUT',body:fs.readFileSync(file)})}
  const blocked=new Set;for(let i=0;i<pending.length;i+=500){const result=await(await this.request('/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:pending.slice(i,i+500)})})).json();for(const r of result.accepted)known[r.key]={revision:r.revision,hash:r.deleted?'':digest(r.value),deleted:r.deleted};this.config.known=known;this.persist();for(const c of result.conflicts){blocked.add(c.local.key);if(!this.config.conflicts?.some(x=>x.local.key===c.local.key&&x.remote?.revision===c.remote?.revision))this.config.conflicts=[...(this.config.conflicts||[]),c];}}
  const remote=(await(await this.request('/records')).json()).records;for(const r of remote.sort((a,b)=>Number(b.key.startsWith('item:'))-Number(a.key.startsWith('item:')))){if(blocked.has(r.key)||known[r.key]?.revision===r.revision)continue;const id=r.key.split(':')[1],live=r.key.startsWith('item:')?this.store.list().find(i=>i.id===id):this.store.note(id),liveValue=live?(r.key.startsWith('item:')?cleanItem(live):live):undefined;if(digest(liveValue??null)!==digest(local.get(r.key)??null)||(r.deleted&&r.key.startsWith('item:')&&this.store.notes(id).some(n=>digest(n)!==digest(local.get('note:'+n.id)??null)))){if(!this.config.conflicts?.some(c=>c.local.key===r.key))this.config.conflicts=[...(this.config.conflicts||[]),{local:{key:r.key,value:liveValue,deleted:!liveValue,revision:known[r.key]?.revision||0},remote:r}];continue}if(r.deleted){if(r.key.startsWith('item:'))this.store.remove(id);else this.store.deleteNote(id);known[r.key]={revision:r.revision,deleted:true,hash:''};continue}const value=r.value;const names=[...(value.shots||[]).map(s=>s.image),value.poster].filter(Boolean);for(const name of names){if(!assetName(name))continue;const dest=path.join(this.store.root,'assets',name);if(!fs.existsSync(dest)){const bytes=Buffer.from(await(await this.request('/assets/'+name)).arrayBuffer());fs.writeFileSync(dest,bytes)}}if(r.key.startsWith('item:')){const old=this.store.list().find(i=>i.id===id);const item={...value,episodes:value.episodes.map(e=>{const original=old?.episodes.find(p=>p.id===e.id);return original?{...e,path:original.path,sourcePath:original.sourcePath,mediaFile:original.mediaFile,subtitle:original.subtitle,cues:original.cues,availableLocally:true}:e})};this.store.put(item);}else{if(!this.store.list().some(i=>i.id===value.itemId))continue;this.store.db.run('INSERT OR REPLACE INTO notes VALUES(?,?,?)',[id,value.itemId,JSON.stringify(value)]);this.store.flush();}known[r.key]={revision:r.revision,hash:digest(value),deleted:false};}
  this.config.known=known;this.config.lastSync=new Date().toISOString();this.lastError='';this.persist();return this.status();
 }catch(e){this.lastError=e.message;throw e}finally{this.running=false}}
}
module.exports={AccountClient,cleanItem};
