const key=p=>String(p||'').toLowerCase();
function validateIds(ids){if(!Array.isArray(ids)||!ids.length||ids.length>10000||ids.some(id=>typeof id!=='string'))throw Error('请选择有效的条目');return [...new Set(ids)]}
function transaction(store,fn){store.db.run('BEGIN');try{const result=fn();store.db.run('COMMIT');store.flush();return result}catch(e){try{store.db.run('ROLLBACK')}catch{}throw e}}
function updateFilms(store,ids,changes){ids=validateIds(ids);const patch={};if('kind'in changes){if(!['movie','series'].includes(changes.kind))throw Error('影片类型无效');patch.kind=changes.kind}if('status'in changes){if(!['want','watching','done'].includes(changes.status))throw Error('观看状态无效');patch.status=changes.status}if('category'in changes)patch.category=String(changes.category).slice(0,500);if('rating'in changes){if(!Number.isInteger(changes.rating)||changes.rating<0||changes.rating>5)throw Error('评分无效');patch.rating=changes.rating}if(!Object.keys(patch).length)throw Error('请选择要修改的内容');const items=ids.map(id=>({...store.get(id),...patch}));transaction(store,()=>{for(const i of items)store.db.run('INSERT OR REPLACE INTO items VALUES(?,?)',[i.id,JSON.stringify(i)])});return {updated:items.length}}
function removeEpisodes(store,episodeIds){const ids=new Set(validateIds(episodeIds)),items=store.list(),episodes=items.flatMap(i=>i.episodes);if([...ids].some(id=>!episodes.some(e=>e.id===id)))throw Error('部分资源已变化，请刷新后重新选择');const candidates=new Map,removedFilms=[],changed=[];
 for(const item of items){const selected=item.episodes.filter(e=>ids.has(e.id));if(!selected.length)continue;for(const ep of selected)if(ep.mediaFile&&ep.verified&&ep.path&&!/^https?:/.test(ep.path))candidates.set(key(ep.path),ep.path);const remaining=item.episodes.filter(e=>!ids.has(e.id));if(!remaining.length)removedFilms.push(item.id);else changed.push({...item,episodes:remaining,lastEpisode:remaining.some(e=>e.id===item.lastEpisode)?item.lastEpisode:remaining[0].id,sessions:(item.sessions||[]).filter(s=>!ids.has(s.episodeId))});}
 transaction(store,()=>{for(const note of store.notes())if(ids.has(note.episodeId))store.db.run('DELETE FROM notes WHERE id=?',[note.id]);for(const id of removedFilms){store.db.run('DELETE FROM notes WHERE itemId=?',[id]);store.db.run('DELETE FROM items WHERE id=?',[id])}for(const i of changed)store.db.run('INSERT OR REPLACE INTO items VALUES(?,?)',[i.id,JSON.stringify(i)])});
 const remaining=new Set(store.list().flatMap(i=>i.episodes.map(e=>key(e.path))));return {removed:ids.size,removedFilms,trashCandidates:[...candidates].filter(([k])=>!remaining.has(k)).map(([,p])=>p),sharedRetained:[...candidates].filter(([k])=>remaining.has(k)).length}
}
function deleteNotes(store,ids){ids=validateIds(ids);if(ids.some(id=>!store.note(id)))throw Error('部分摘记已变化，请刷新后重新选择');transaction(store,()=>{for(const id of ids)store.db.run('DELETE FROM notes WHERE id=?',[id])});return {removed:ids.length}}
function updateNotes(store,ids,{tags,color}){ids=validateIds(ids);const notes=ids.map(id=>{const n=store.note(id);if(!n)throw Error('部分摘记已变化，请刷新后重新选择');return {...n,...(tags===undefined?{}:{tags:String(tags).slice(0,500)}),...(['gold','purple','green'].includes(color)?{color}:{}),updated:new Date().toISOString()}});transaction(store,()=>{for(const n of notes)store.db.run('INSERT OR REPLACE INTO notes VALUES(?,?,?)',[n.id,n.itemId,JSON.stringify(n)])});return {updated:notes.length}}
module.exports={validateIds,updateFilms,removeEpisodes,deleteNotes,updateNotes};

