const fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),iconv=require('iconv-lite');
const VIDEO=/\.(mp4|mkv|avi|mov|m4v|webm|wmv|flv|ts|m2ts|mts|mpg|mpeg|vob|ogv|3gp)$/i;
const natural=new Intl.Collator('zh-CN',{numeric:true,sensitivity:'base'});
function url(value){let s=String(value||'').trim();if(!/^[a-z][\w+.-]*:/i.test(s))s='https://'+s;let u;try{u=new URL(s)}catch{throw Error('请输入有效的网址')}if(!['https:','http:'].includes(u.protocol)||!u.hostname||u.username||u.password)throw Error('只支持不含账号密码的 HTTP / HTTPS 链接');return u.href;}
function time(value){if(typeof value==='number')return value;const v=String(value).trim().replace(',','.').split(':').map(Number);if(v.some(x=>!Number.isFinite(x)))return NaN;return v.reduce((a,b)=>a*60+b,0);}
function stamp(t){t=Math.max(0,Number(t)||0);return [Math.floor(t/3600),Math.floor(t/60)%60,Math.floor(t)%60].map(x=>String(x).padStart(2,'0')).join(':');}
function clean(s){return s.replace(/<[^>]*>/g,'').replace(/\{[^}]*\}/g,'').replace(/\\[Nn]/g,'\n').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').trim();}
function subtitles(text){text=text.replace(/^\uFEFF/,'').replace(/\r/g,'');const out=[];if(/^\[Events\]/im.test(text)){let columns=['layer','start','end','style','name','marginl','marginr','marginv','effect','text'];for(const line of text.split('\n')){if(/^Format:/i.test(line)&&line.toLowerCase().includes('start'))columns=line.slice(7).trim().toLowerCase().split(/,\s*/);if(!/^Dialogue:/i.test(line))continue;const raw=line.slice(9).trim().split(','),values=raw.slice(0,columns.length-1).concat(raw.slice(columns.length-1).join(','));out.push({start:time(values[columns.indexOf('start')]),end:time(values[columns.indexOf('end')]),text:clean(values[columns.indexOf('text')]||'')});}}else{for(const block of text.split(/\n\s*\n/)){const lines=block.split('\n'),index=lines.findIndex(l=>l.includes('-->'));if(index<0)continue;const parts=lines[index].trim().split(/\s+-->\s+/);out.push({start:time(parts[0]),end:time(parts[1]?.split(/\s+/)[0]),text:clean(lines.slice(index+1).join('\n'))});}}return out.filter(x=>Number.isFinite(x.start)&&Number.isFinite(x.end)&&x.end>x.start&&x.text).sort((a,b)=>a.start-b.start).map((x,i)=>({...x,id:i}));}
function readText(file){const bytes=fs.readFileSync(file);if(bytes[0]===255&&bytes[1]===254)return iconv.decode(bytes,'utf16-le');let s=bytes.toString('utf8');if(s.includes('\ufffd'))s=iconv.decode(bytes,'gb18030');return s;}
function walk(folder){const files=[];for(const ent of fs.readdirSync(folder,{withFileTypes:true})){if(ent.isSymbolicLink())continue;const p=path.join(folder,ent.name);if(ent.isDirectory())files.push(...walk(p));else if(VIDEO.test(p))files.push(p);}return files.sort(natural.compare);}
function episode(file){const title=path.basename(file,path.extname(file));let m=title.match(/S(\d{1,2})[ ._-]*E(\d{1,3})/i);if(m)return {title,season:+m[1],episode:+m[2]};m=title.match(/(?:第\s*(\d+)\s*集|(?:EP?|第)[ ._-]*(\d{1,3})|^(\d{1,3})(?:\D|$))/i);return {title,season:1,episode:m?+(m[1]||m[2]||m[3]):0};}
function validateNote(n,item){const start=Number(n.start),end=Number(n.end);if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<start||(n.kind==='quote'&&end<=start))throw Error('请填写有效的起止时间，片段结束需晚于开始');const ep=item.episodes.find(e=>e.id===n.episodeId);if(!ep)throw Error('笔记对应的影片已不存在');if(ep.duration&&end>ep.duration+1)throw Error('笔记时间超出影片长度');if(!['quote','frame','shot'].includes(n.kind))throw Error('未知笔记类型');return {...n,start,end,text:String(n.text||'').slice(0,20000),comment:String(n.comment||'').slice(0,20000),tags:String(n.tags||'').slice(0,500),color:['gold','purple','green'].includes(n.color)?n.color:'gold',shots:(n.shots||[]).slice(0,20)};}
module.exports={VIDEO,natural,url,time,stamp,subtitles,readText,walk,episode,validateNote};
