const {app,BrowserWindow,ipcMain,dialog,shell,protocol,net,nativeImage,safeStorage}=require('electron');
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),{randomUUID}=require('node:crypto'),Zip=require('adm-zip');
const batch=require('./batch.cjs');
let managementBusy=false,lastDoubleClick={time:0,source:''};
function videoDoubleClick(source){if(closing||!active||hidden||busy)return;const now=Date.now();if(source!==lastDoubleClick.source&&now-lastDoubleClick.time<120)return;lastDoubleClick={time:now,source};return handlers.control('toggle')}
const {createService}=require('./account-service.cjs'),{AccountClient}=require('./account-client.cjs');
let accountService,accountClient,accountTimer,accountServiceError='';
const {Surface}=require('./surface.cjs');
const {Vault,verifiedCopy}=require('./vault.cjs');
const {Store}=require('./store.cjs'),{Player}=require('./player.cjs'),core=require('./core.cjs');
protocol.registerSchemesAsPrivileged([{scheme:'gyasset',privileges:{standard:true,secure:true,supportFetchAPI:true,corsEnabled:true}}]);
if(process.env.GUANYING_DATA)app.setPath('userData',path.resolve(process.env.GUANYING_DATA));
let win,surface,player,store,vault,active,rect,hidden=false,busy=false,closing=false,reviewEnd=null,reviewLoop=false,reviewStart=0,tick,sessionInfo,recording=null,recordCapture=null;
function emit(channel,data){if(win&&!win.isDestroyed())win.webContents.send('gy:'+channel,data);}
function assetPath(name){if(typeof name!=='string'||path.basename(name)!==name||!/^[-\w]+\.(png|jpg|jpeg|webp)$/i.test(name))throw Error('图片路径无效');return path.join(store.root,'assets',name);}
function syncSurface(){if(!surface||surface.isDestroyed())return;if(!rect||hidden||!active||win.isMinimized()||!win.isVisible()){surface.hide();return;}const scale=win.webContents.getZoomFactor()*(require('electron').screen.getDisplayMatching(win.getBounds()).scaleFactor||1);surface.setBounds({x:Math.round(rect.x*scale),y:Math.round(rect.y*scale),width:Math.max(16,Math.round(rect.width*scale)),height:Math.max(16,Math.round(rect.height*scale))});if(!surface.isVisible())surface.showInactive();}
async function nativeDialog(method,options){const was=hidden;hidden=true;syncSurface();try{return await dialog[method](win,options)}finally{hidden=was;syncSurface()}}
function snapshot(){return {...(player?.state||{}),active,reviewEnd,reviewLoop,busy};}
function progress(){if(!active||!player||busy)return;store.progress(active.itemId,active.episodeId,player.state['time-pos'],player.state.duration,sessionInfo?.seconds>=10?sessionInfo:undefined);}
function imageCopy(input){const name=randomUUID()+path.extname(input).toLowerCase();if(!['.png','.jpg','.jpeg','.webp'].includes(path.extname(name)))throw Error('请选择 PNG / JPG / WebP 图片');if(nativeImage.createFromPath(input).isEmpty())throw Error('图片无法读取');fs.copyFileSync(input,assetPath(name));return name;}
async function ensurePlayer(){if(player&&!player.dead)return;const root=app.isPackaged?process.resourcesPath:path.join(__dirname,'..','vendor');const handle=win.getNativeWindowHandle();const parent=handle.length>=8?handle.readBigUInt64LE().toString():handle.readUInt32LE().toString();surface=await Surface.open(path.join(root,'host','VideoHost.exe'),parent);surface.on('double-click',()=>{Promise.resolve(videoDoubleClick('native')).catch(e=>emit('error',e.message));});const wid=surface.wid;const executable=path.join(app.isPackaged?process.resourcesPath:path.join(__dirname,'..','vendor'),'mpv','mpv.exe');player=new Player(executable,wid,app.isPackaged?path.join(process.resourcesPath,'host','keys.lua'):path.join(__dirname,'keys.lua'),path.join(store.root,'player.log'));player.on('failure',m=>emit('error',m));player.on('exit',code=>{if(!closing){emit('error','播放引擎已退出'+(code?'（'+code+'）':''));surface?.hide();}});let last=0;player.on('state',(_,name)=>{if(name==='sub-text'&&recording&&player.state['sub-text']&&!busy)queueRecordedShot();if(Date.now()-last>120){last=Date.now();emit('state',snapshot())}});player.on('client-message',m=>{if(m.args?.[0]==='guanying-key')emit('key',m.args[1]);});player.on('end-file',m=>{if(m.reason==='error')emit('error','无法播放此文件或链接：'+(m.file_error||'请检查来源'));});await player.connect();const settings=store.getSetting('preferences')||{};await player.command(['set_property','volume',settings.volume??70]);await player.command(['set_property','speed',1]);}
function queueRecordedShot(){const rec=recording;if(!rec||recordCapture||rec.shots.length>=20)return;const text=player.state['sub-text'];if(!text||rec.shots.at(-1)?.text===text)return;recordCapture=(async()=>{await new Promise(r=>setTimeout(r,100));if(recording!==rec||busy)return;const shot=await capture();rec.shots.push({...shot,text});})().catch(e=>emit('error','片段截图未能保存：'+e.message)).finally(()=>{recordCapture=null;});}
async function play(itemId,episodeId,start,end,loop=false){if(busy)throw Error('正在整理截图，请稍候');progress();recording=null;const item=store.get(itemId),ep=item.episodes.find(e=>e.id===episodeId)||item.episodes.find(e=>e.id===item.lastEpisode)||item.episodes[0];if(!/^https?:\/\//.test(ep.path)&&!fs.existsSync(ep.path))throw Error('原视频已移动或磁盘未连接。请在影片详情中点击“重新关联文件”。');await ensurePlayer();const wasSame=active?.episodeId===ep.id;active={itemId,episodeId:ep.id};reviewEnd=Number.isFinite(end)?end:null;reviewLoop=!!loop;reviewStart=Number(start)||0;sessionInfo={id:randomUUID(),date:new Date().toISOString(),episodeId:ep.id,seconds:0};busy=true;try{if(wasSame&&Number.isFinite(start))await player.seek(start);else {await player.load(ep.path,Number.isFinite(start)?start:ep.position||0);if(ep.subtitle&&fs.existsSync(path.join(store.root,ep.subtitle)))await player.command(['sub-add',path.join(store.root,ep.subtitle),'select']);}await player.command(['set_property','sub-delay',ep.subDelay||0]);await player.command(['set_property','pause',false]);busy=false;syncSurface();if(!item.poster){setTimeout(async()=>{if(active?.episodeId!==ep.id||busy)return;try{const shot=await capture('video');const fresh=store.get(itemId);if(!fresh.poster)store.update(itemId,{poster:shot.image});}catch{}},1700);}return {item:store.get(itemId),episode:ep};}catch(e){busy=false;active=null;surface.hide();throw e;}}
async function capture(mode='subtitles'){if(!active||!player)throw Error('请先播放影片');const pos=await player.command(['get_property','time-pos']);if(!Number.isFinite(pos))throw Error('影片仍在加载，请稍候');const image=randomUUID()+'.png';await player.command(['screenshot-to-file',assetPath(image),mode==='video'?'video':'subtitles']);const size=nativeImage.createFromPath(assetPath(image)).getSize();return {image,time:pos,text:player.state['sub-text']||'',width:size.width,height:size.height};}
async function captureCues(cues){if(busy)throw Error('正在整理截图，请稍候');if(!active)throw Error('请先播放影片');if(!Array.isArray(cues)||!cues.length||cues.length>20)throw Error('每次请选择 1–20 句台词');const duration=player.state.duration;for(const c of cues)if(!Number.isFinite(c.start)||!Number.isFinite(c.end)||c.start<0||c.end<=c.start||c.end>duration+1)throw Error('字幕时间无效');const current=player.state['time-pos']||0,paused=player.state.pause;busy=true;emit('state',snapshot());try{await player.command(['set_property','pause',true]);const shots=[];for(const c of cues){await player.seek(Math.min(duration-.02,c.start+Math.min(.25,(c.end-c.start)/2)));const shot=await capture();shots.push({...shot,text:c.text||shot.text});}return shots;}finally{try{await player.seek(current);await player.command(['set_property','pause',!!paused]);}finally{busy=false;emit('state',snapshot());}}}
function makeBackup(file){store.flush();const zip=new Zip;zip.addFile('manifest.json',Buffer.from(JSON.stringify({app:'guanying-diary',version:1,created:new Date().toISOString(),videos:'managed-media-not-included'})));zip.addLocalFile(store.file);for(const folder of ['assets','subtitles'])if(fs.existsSync(path.join(store.root,folder)))zip.addLocalFolder(path.join(store.root,folder),folder);zip.writeZip(file+'.tmp');fs.renameSync(file+'.tmp',file);return file;}
function markdown(notes){return '# 观影日记\n\n'+notes.map(n=>{const i=store.get(n.itemId),ep=i.episodes.find(e=>e.id===n.episodeId);return `## ${i.title} · ${n.kind==='quote'?'台词片段':n.kind==='frame'?'画面收藏':'截图'}\n\n- 集数：${ep?.title||''}\n- 时间：${core.stamp(n.start)} — ${core.stamp(n.end)}\n- 日期：${n.created}\n- 标签：${n.tags||''}\n\n${n.text?'> '+n.text.replace(/\n/g,'\n> '):''}\n\n${n.comment||''}\n\n${n.shots.map(s=>`![${core.stamp(s.time)}](images/${s.image})`).join('\n\n')}\n`;}).join('\n');}
function batchBackup(){progress();const folder=path.join(store.root,'backups');fs.mkdirSync(folder,{recursive:true});return makeBackup(path.join(folder,'before-batch-'+Date.now()+'.zip'))}
async function management(fn){if(managementBusy||busy||vault.state.running||accountClient.running)throw Error('正在处理资源或同步，请稍后再试');managementBusy=true;try{return await fn()}finally{managementBusy=false}}
async function trashCopies(paths){const failed=[];for(const p of [...new Set(paths)]){try{if(fs.existsSync(p))await shell.trashItem(p)}catch(e){failed.push({path:p,error:e.message})}}return failed}
async function removeBatchEpisodes(ids,deleteMedia=false){return management(async()=>{batch.validateIds(ids);const all=store.list().flatMap(i=>i.episodes);if(ids.some(id=>!all.some(e=>e.id===id)))throw Error('选中资源已变化，请刷新');if(active&&ids.includes(active.episodeId))await handlers.stop();const backup=batchBackup(),result=batch.removeEpisodes(store,ids);const failed=deleteMedia?await trashCopies(result.trashCandidates):[];return {...result,backup,failed}})}
async function exportSelectedNotes(notes){if(!notes.length)throw Error('所选条目没有摘记');const r=await nativeDialog('showSaveDialog',{title:'导出所选图文笔记',defaultPath:'观影所选笔记.zip',filters:[{name:'Markdown 与原图',extensions:['zip']}]});if(r.canceled)return null;const z=new Zip;z.addFile('观影笔记.md',Buffer.from(markdown(notes)));for(const name of new Set(notes.flatMap(n=>n.shots.map(s=>s.image))))if(fs.existsSync(assetPath(name)))z.addLocalFile(assetPath(name),'images');z.writeZip(r.filePath);return r.filePath}
const handlers={
 videoDoubleClick:()=>videoDoubleClick('renderer'),
 batchUpdateFilms:(ids,patch)=>management(()=>batch.updateFilms(store,ids,patch)),batchRemoveFilms:async(ids,deleteMedia=false)=>{ids=batch.validateIds(ids);const eps=ids.flatMap(id=>store.get(id).episodes.map(e=>e.id));return removeBatchEpisodes(eps,deleteMedia)},batchRemoveEpisodes:removeBatchEpisodes,
 batchDeleteNotes:ids=>management(()=>{batch.validateIds(ids);const backup=batchBackup();return {...batch.deleteNotes(store,ids),backup}}),batchUpdateNotes:(ids,patch)=>management(()=>batch.updateNotes(store,ids,patch)),
 batchExport:({itemIds,episodeIds,noteIds})=>{const items=new Set(itemIds||[]),eps=new Set(episodeIds||[]),notes=new Set(noteIds||[]);return exportSelectedNotes(store.notes().filter(n=>items.has(n.itemId)||eps.has(n.episodeId)||notes.has(n.id)))},
 batchTrashResources:paths=>management(async()=>{if(!Array.isArray(paths)||!paths.length)throw Error('请选择未入库的影库副本');const inventory=handlers.resources();if(paths.some(p=>!inventory.some(e=>e.orphan&&e.mediaFile&&e.path===p)))throw Error('仅可清理没有片库引用的影库副本');const failed=await trashCopies(paths);return {removed:paths.length-failed.length,failed}}),

 accountStatus:()=>({...accountClient.status(),localError:accountServiceError}),accountLogin:async input=>{if(input.migrate){const folder=path.join(store.root,'backups');fs.mkdirSync(folder,{recursive:true});makeBackup(path.join(folder,'before-account-change-'+Date.now()+'.zip'));}return accountClient.login(input)},accountLogout:()=>accountClient.logout(),accountSync:()=>{if(managementBusy)throw Error('正在批量处理，请稍后同步');return accountClient.sync()},accountConflicts:()=>accountClient.config.conflicts||[],accountResolve:(key,choice)=>accountClient.resolve(key,choice),openExtension:()=>shell.openPath(app.isPackaged?path.join(process.resourcesPath,'bilibili-extension'):path.join(__dirname,'..','extension')),openWebNote:(id,epId,start,end,loop)=>{const ep=store.get(id).episodes.find(e=>e.id===epId)||store.get(id).episodes[0];const u=new URL(ep.path);if(u.hostname!=='www.bilibili.com'||!/^\/(video|bangumi)\//.test(u.pathname))throw Error('仅支持 B 站网页视频');u.searchParams.set('t',String(Math.max(0,Number(start)||0)));if(Number.isFinite(end)&&end>start)u.searchParams.set('gy_end',String(end));if(loop)u.searchParams.set('gy_loop','1');return shell.openExternal(u.href)},
 resources:()=>{const refs=store.list().flatMap(i=>i.episodes.map(e=>({itemId:i.id,title:i.title,kind:i.kind,...e})));const inventory=store.getSetting('mediaInventory')||{};const folders=[...new Set([vault.folder(),...Object.keys(inventory).map(p=>path.dirname(p)),...refs.filter(e=>e.mediaFile).map(e=>path.dirname(e.path))])];for(const folder of folders)if(fs.existsSync(folder))for(const name of fs.readdirSync(folder)){const p=path.join(folder,name);if(core.VIDEO.test(name)&&!refs.some(e=>e.path===p))refs.push({...inventory[p],path:p,title:inventory[p]?.originalName||name,mediaFile:name,bytes:fs.statSync(p).size,orphan:true});}return refs;},
 recognizeSubtitle:async name=>{const file=assetPath(name);const script=app.isPackaged?path.join(process.resourcesPath,'host','Read-Subtitle.ps1'):path.join(__dirname,'Read-Subtitle.ps1');return new Promise((resolve,reject)=>{require('node:child_process').execFile('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',script,'-ImagePath',file],{windowsHide:true,timeout:30000,maxBuffer:1024*1024,encoding:'utf8'},(error,stdout)=>{if(error)return reject(Error('画面字幕识别不可用，请核对 Windows 文字识别语言包'));try{resolve(JSON.parse(stdout.trim()).text||'');}catch{reject(Error('画面字幕识别失败'));}});});},
 deleteResource:async p=>{const entry=handlers.resources().find(e=>e.path===p&&e.orphan&&e.mediaFile);if(!entry)throw Error('仅能删除没有片库记录引用的影库副本');await shell.trashItem(p);return true;},
 init:()=>({items:store.list(),notes:store.notes(),sources:store.getSetting('sources'),settings:store.getSetting('preferences')||{},storage:vault.info(),importState:vault.state,version:app.getVersion()}),
 importFiles:async(options={})=>{const r=await nativeDialog('showOpenDialog',{title:'选择要保存到观影的资源',properties:['openFile','multiSelections'],filters:[{name:'视频',extensions:['mp4','mkv','avi','mov','m4v','webm','wmv','flv','ts','m2ts','mpg','mpeg','vob','mts','ogv','3gp']}]});return r.canceled?null:vault.import(r.filePaths,options)},
 importFolder:async(options={})=>{const r=await nativeDialog('showOpenDialog',{title:'选择影片文件夹（包含子文件夹）',properties:['openDirectory']});return r.canceled?null:vault.import(r.filePaths,{...options,title:options.title||path.basename(r.filePaths[0])})},
 importPaths:(paths,options={})=>vault.import(paths,options),
 cancelImport:()=>vault.cancel(),
 resolveDuplicates:action=>vault.resolveDuplicates(action),
 preserveExisting:()=>vault.preserveExisting(),
 storageInfo:()=>vault.info(),
 chooseStorage:async()=>{if(vault.state.running)throw Error('请等当前导入完成再更换位置');const r=await nativeDialog('showOpenDialog',{title:'选择影库保存位置（新导入的影片存放在这里）',properties:['openDirectory','createDirectory']});if(r.canceled)return null;const folder=path.resolve(r.filePaths[0]),program=path.resolve(path.dirname(app.getPath('exe')));if(folder.toLowerCase()===program.toLowerCase()||folder.toLowerCase().startsWith(program.toLowerCase()+path.sep))throw Error('请选择独立的影库目录，不要放在软件安装目录中');store.setting('mediaFolder',folder);return vault.info()},
 openStorage:()=>shell.openPath(vault.folder()),
 addUrl:({title,url})=>{const address=core.url(url);if(!String(title).trim())throw Error('请填写片名');const result=store.import([address]);const item=store.list().find(i=>i.episodes[0].path===address);store.update(item.id,{title});return result},
 updateItem:(id,changes)=>store.update(id,changes),
 removeItem:async(id,deleteMedia=false)=>{if(active?.itemId===id)await handlers.stop();const item=store.get(id);const media=[...new Set(item.episodes.filter(e=>e.mediaFile&&e.verified).map(e=>e.path) )];store.remove(id);if(deleteMedia)for(const p of media){const used=store.list().some(i=>i.episodes.some(e=>e.path===p));if(!used&&!/^https?:/.test(p))await shell.trashItem(p);}},
 beginRange:async()=>{if(!active||busy)throw Error('请先打开影片');const start=await player.command(['get_property','time-pos']);recording={start,shots:[]};queueRecordedShot();return start},endRange:async()=>{const rec=recording;if(!rec)return null;await recordCapture;recording=null;return rec},play,stop:async()=>{progress();recording=null;active=null;reviewEnd=null;if(player&&!player.dead)await player.command(['stop']);surface?.hide();return true},
 control:async(action,value)=>{if(!player||!active)throw Error('请先打开影片');if(busy)throw Error('正在生成截图，请稍候');const map={toggle:['cycle','pause'],pause:['set_property','pause',!!value],seek:['seek',Math.max(0,Number(value)||0),'absolute+exact'],relative:['seek',Math.max(-600,Math.min(600,Number(value)||0)),'relative+exact'],speed:['set_property','speed',[1,1.25,1.5,2].includes(Number(value))?Number(value):1],volume:['set_property','volume',Math.max(0,Math.min(100,Number(value)||0))],mute:['cycle','mute'],nextFrame:['frame-step'],previousFrame:['frame-back-step'],audio:['set_property','aid',value==='no'?'no':Number(value)],subtitle:['set_property','sid',value==='no'?'no':Number(value)],subDelay:['set_property','sub-delay',Math.max(-120,Math.min(120,Number(value)||0))]};if(action==='clearReview'){reviewEnd=null;reviewLoop=false;await player.command(['set_property','ab-loop-a','no']);await player.command(['set_property','ab-loop-b','no']);emit('state',snapshot());return;}if(!map[action])throw Error('未知播放器操作');if(action==='seek'||action==='relative')reviewEnd=null;const result=await player.command(map[action]);if(action==='subDelay'){const item=store.get(active.itemId);item.episodes.find(e=>e.id===active.episodeId).subDelay=Number(value)||0;store.put(item);}if(action==='volume')store.setting('preferences',{...store.getSetting('preferences'),volume:Math.max(0,Math.min(100,Number(value)||0))});return result;},
 bounds:r=>{if(r&&[r.x,r.y,r.width,r.height].every(Number.isFinite))rect=r;else rect=null;syncSurface()},
 previewHidden:v=>{hidden=!!v;syncSurface()},
 capture:async(mode)=>{if(busy)throw Error('正在生成截图');return capture(mode)},captureCues,
 saveNote:n=>{for(const s of n.shots||[])if(!fs.existsSync(assetPath(s.image)))throw Error('笔记图片丢失');return store.saveNote(n)},
 deleteNote:id=>store.deleteNote(id),listNotes:id=>store.notes(id),
 loadSubtitles:async(itemId,episodeId)=>{const r=await nativeDialog('showOpenDialog',{title:'添加外挂字幕',properties:['openFile'],filters:[{name:'字幕',extensions:['srt','vtt','ass','ssa']}]});if(r.canceled)return null;const file=r.filePaths[0],cues=core.subtitles(core.readText(file));const folder=path.join(store.root,'subtitles');fs.mkdirSync(folder,{recursive:true});const sub='subtitles/'+randomUUID()+path.extname(file);fs.copyFileSync(file,path.join(store.root,sub));const i=store.get(itemId),ep=i.episodes.find(e=>e.id===episodeId);if(!ep)throw Error('剧集不存在');ep.subtitle=sub;ep.cues=cues;store.put(i);if(active?.episodeId===ep.id)await player.command(['sub-add',path.join(store.root,sub),'select']);return {cues};},
 relink:async(itemId,episodeId)=>{const r=await nativeDialog('showOpenDialog',{title:'重新关联原视频',properties:['openFile']});if(r.canceled)return null;if(!core.VIDEO.test(r.filePaths[0]))throw Error('请选择视频文件');if(vault.state.running)throw Error('请等当前资源保存完成');const saved=await verifiedCopy(r.filePaths[0],vault.folder());const i=store.get(itemId),ep=i.episodes.find(e=>e.id===episodeId);Object.assign(ep,saved);store.put(i);return i;},
 poster:async id=>{const r=await nativeDialog('showOpenDialog',{title:'设置影片封面',properties:['openFile'],filters:[{name:'图片',extensions:['png','jpg','jpeg','webp']}]});if(r.canceled)return null;return store.update(id,{poster:imageCopy(r.filePaths[0])})},
 saveSource:s=>store.saveSource(s),deleteSource:id=>{store.setting('sources',store.getSetting('sources').filter(s=>s.id!==id));return store.getSetting('sources')},openSource:id=>{const s=store.getSetting('sources').find(s=>s.id===id);if(!s)throw Error('网站已不存在');return shell.openExternal(core.url(s.url))},
 backup:async()=>{progress();const r=await nativeDialog('showSaveDialog',{title:'备份日记、字幕和截图',defaultPath:'观影备份-'+new Date().toISOString().slice(0,10)+'.zip',filters:[{name:'观影备份',extensions:['zip']}]});return r.canceled?null:makeBackup(r.filePath)},
 restore:async()=>{if(vault.state.running)throw Error('请等影片保存完成再恢复备份');const r=await nativeDialog('showOpenDialog',{title:'恢复观影备份',filters:[{name:'观影备份',extensions:['zip']}],properties:['openFile']});if(r.canceled)return null;const z=new Zip(r.filePaths[0]),manifest=JSON.parse(z.readAsText('manifest.json'));if(manifest.app!=='guanying-diary'||manifest.version!==1)throw Error('不是兼容的观影备份');const entries=z.getEntries();for(const e of entries){if(e.entryName.includes('..')||e.entryName.includes('\\')||!(/^(manifest\.json|diary\.sqlite|assets\/[-\w]+\.(png|jpg|jpeg|webp)|subtitles\/[-\w]+\.(srt|vtt|ass|ssa)|assets\/|subtitles\/)$/.test(e.entryName)))throw Error('备份内存在无效文件');}const bytes=z.readFile('diary.sqlite'),candidate=new store.SQL.Database(bytes);try{if(candidate.exec('PRAGMA integrity_check')[0]?.values[0]?.[0]!=='ok')throw Error('数据库损坏');for(const table of ['items','notes']){const rows=candidate.exec(`SELECT value FROM ${table}`)[0]?.values||[];for(const row of rows)JSON.parse(row[0]);}candidate.exec('SELECT key,value FROM settings');}finally{candidate.close();}const confirm=await nativeDialog('showMessageBox',{type:'question',buttons:['取消','备份当前数据并恢复'],defaultId:0,cancelId:0,message:'用这个备份恢复观影日记？',detail:'会先保存当前笔记备份。视频副本不会删除；换机时还需带上影库视频文件。'});if(confirm.response!==1)return null;await handlers.stop();const safety=path.join(store.root,'backups');fs.mkdirSync(safety,{recursive:true});makeBackup(path.join(safety,'before-restore-'+Date.now()+'.zip'));for(const e of entries)if(/^(assets|subtitles)\//.test(e.entryName)&&!e.isDirectory){const dest=path.join(store.root,e.entryName);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,e.getData());}fs.writeFileSync(store.file+'.restore',bytes);store.db.close();fs.renameSync(store.file+'.restore',store.file);store=await Store.open(store.root);vault.store=store;accountClient.store=store;return true;},
 exportMarkdown:async itemId=>{const notes=store.notes(itemId);const r=await nativeDialog('showSaveDialog',{title:'导出图文笔记',defaultPath:'观影笔记.zip',filters:[{name:'Markdown 与原图',extensions:['zip']}]});if(r.canceled)return null;const z=new Zip;z.addFile('观影笔记.md',Buffer.from(markdown(notes)));for(const name of new Set(notes.flatMap(n=>n.shots.map(s=>s.image))))if(fs.existsSync(assetPath(name)))z.addLocalFile(assetPath(name),'images');z.writeZip(r.filePath);return r.filePath},
 exportImage:async(data,name='台词拼图')=>{if(typeof data!=='string'||!data.startsWith('data:image/png;base64,')||data.length>350000000)throw Error('导出图片格式或大小无效');const bytes=Buffer.from(data.split(',')[1],'base64');if(nativeImage.createFromBuffer(bytes).isEmpty())throw Error('图片生成失败');const r=await nativeDialog('showSaveDialog',{title:'保存原尺寸 PNG',defaultPath:name.replace(/[<>:"/\\|?*]/g,'_')+'.png',filters:[{name:'PNG 图片',extensions:['png']}]});if(r.canceled)return null;fs.writeFileSync(r.filePath,bytes);return r.filePath},
 exportShot:async name=>{const input=assetPath(name);const r=await nativeDialog('showSaveDialog',{title:'保存原尺寸截图',defaultPath:'观影截图.png',filters:[{name:'PNG',extensions:['png']}]});if(r.canceled)return null;fs.copyFileSync(input,r.filePath);return r.filePath},
 saveSettings:s=>{const prev=store.getSetting('preferences')||{};store.setting('preferences',{...prev,...s})},openData:()=>shell.openPath(store.root),fullscreen:value=>{win.setFullScreen(typeof value==='boolean'?value:!win.isFullScreen());setTimeout(syncSurface,200);return win.isFullScreen()}
};
if(!app.requestSingleInstanceLock())app.quit();else{
app.on('second-instance',()=>{if(win){win.restore();win.show();win.focus()}});
app.whenReady().then(async()=>{store=await Store.open(app.getPath('userData'));try{accountService=await createService(path.join(store.root,'account-service'),{port:process.env.GUANYING_DATA?0:48721})}catch(e){accountServiceError='本机插件服务未启动：'+e.message}accountClient=new AccountClient(store,safeStorage,accountService?.url||'http://127.0.0.1:48721');accountTimer=setInterval(()=>{if(accountClient.config.token&&!closing&&!vault.state.running&&!managementBusy)accountClient.sync().then(()=>emit('account',accountClient.status())).catch(()=>{})},20000);vault=new Vault(store,process.env.GUANYING_DATA?path.join(store.root,'media'):path.join(app.getPath('videos'),'观影影库'),s=>emit('import',s));protocol.handle('gyasset',async request=>{try{const name=decodeURIComponent(new URL(request.url).pathname.slice(1));const response=await net.fetch(pathToFileURL(assetPath(name)).href);const headers=new Headers(response.headers);headers.set('Access-Control-Allow-Origin','*');return new Response(response.body,{status:response.status,headers})}catch{return new Response('Not found',{status:404})}});win=new BrowserWindow({width:1380,height:900,minWidth:1000,minHeight:680,backgroundColor:'#17171c',title:'观影',icon:path.join(__dirname,'ui','icon.ico'),autoHideMenuBar:true,show:false,webPreferences:{preload:path.join(__dirname,'preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true}});win.setMenu(null);win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.webContents.session.setPermissionRequestHandler((wc,permission,cb)=>cb(false));for(const [name,fn]of Object.entries(handlers))ipcMain.handle('gy:'+name,async(e,...args)=>{if(e.sender!==win.webContents)throw Error('Invalid sender');return fn(...args)});await win.loadFile(path.join(__dirname,'ui','index.html'));win.show();for(const event of ['move','resize','restore','show','enter-full-screen','leave-full-screen'])win.on(event,syncSurface);win.on('minimize',()=>surface?.hide());win.on('hide',()=>surface?.hide());let timerCount=0;tick=setInterval(()=>{if(active&&player&&!busy){if(!player.state.pause)sessionInfo.seconds+=.25;if(++timerCount%20===0)progress();const t=player.state['time-pos'];if(reviewEnd!==null&&t>=reviewEnd){if(reviewLoop){player.command(['seek',reviewStart,'absolute+exact']).catch(()=>{});}else{player.command(['set_property','pause',true]).catch(()=>{});reviewEnd=null;}}emit('state',snapshot());}},250);win.on('close',e=>{if(closing)return;e.preventDefault();if(managementBusy){emit('error','正在完成批量操作，请稍后退出');return;}if(vault.state.running){emit('error','资源正在保存，请等完成，或在导入窗口取消后再退出');return;}closing=true;clearInterval(tick);clearInterval(accountTimer);progress();(async()=>{await player?.close();while(accountClient.running)await new Promise(r=>setTimeout(r,100));await accountService?.close();store.flush();surface?.destroy();win.destroy();app.quit();})();});}).catch(e=>{dialog.showErrorBox('观影启动失败',e.message);app.quit()});
app.on('window-all-closed',()=>app.quit());
}
