const net=require('node:net'),{spawn}=require('node:child_process'),{EventEmitter}=require('node:events');
class Player extends EventEmitter{
 constructor(exe,wid,script,log){super();this.seq=0;this.pending=new Map;this.state={};this.pipe='\\\\.\\pipe\\guanying-'+process.pid+'-'+Date.now();this.proc=spawn(exe,['--no-config','--idle=yes','--keep-open=yes','--force-window=yes','--osc=no','--input-default-bindings=no','--input-vo-keyboard=yes','--input-cursor=yes','--input-builtin-dragging=no','--input-doubleclick-time=500','--input-ipc-server='+this.pipe,'--wid='+wid,'--hwdec=auto-safe','--vo=gpu','--gpu-api=d3d11','--video-sync=display-resample','--volume-max=100','--screenshot-format=png','--screenshot-png-compression=3','--sub-auto=fuzzy','--sub-codepage=auto','--script='+script,'--log-file='+log],{windowsHide:true,stdio:'ignore'});this.proc.on('error',e=>this.emit('failure',e.message));this.proc.on('exit',(code)=>{this.dead=true;this.socket?.destroy();for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error('播放引擎已退出'));}this.pending.clear();this.emit('exit',code);});}
 async connect(){for(let i=0;i<100;i++){if(this.dead)throw Error('播放引擎启动失败');try{this.socket=await new Promise((resolve,reject)=>{const c=net.connect(this.pipe);c.once('error',reject);c.once('connect',()=>{c.removeListener('error',reject);resolve(c);});});break}catch{await new Promise(r=>setTimeout(r,60));}}if(!this.socket)throw Error('播放引擎连接超时');let buffer='';this.socket.on('error',e=>this.emit('failure',e.message));this.socket.on('data',chunk=>{buffer+=chunk;let idx;while((idx=buffer.indexOf('\n'))>=0){let line=buffer.slice(0,idx);buffer=buffer.slice(idx+1);try{this.message(JSON.parse(line));}catch{}}});const props=['time-pos','duration','pause','volume','speed','mute','sub-text','sub-start','sub-end','track-list','video-params','video-dec-params','hwdec-current','eof-reached','sid','aid','sub-delay','chapter-list','seeking'];for(let i=0;i<props.length;i++)await this.command(['observe_property',i+1,props[i]]);return this;}
 message(m){if(m.request_id){const p=this.pending.get(m.request_id);if(p){clearTimeout(p.timer);this.pending.delete(m.request_id);if(m.error==='success')p.resolve(m.data);else p.reject(Error(m.error));}}if(m.event==='property-change'){this.state[m.name]=m.data;this.emit('state',this.state,m.name);}if(m.event)this.emit(m.event,m);}
 command(command){return new Promise((resolve,reject)=>{if(!this.socket||this.socket.destroyed)return reject(Error('播放引擎尚未连接'));const request_id=++this.seq;const timer=setTimeout(()=>{this.pending.delete(request_id);reject(Error('播放器操作超时'));},15000);this.pending.set(request_id,{resolve,reject,timer});this.socket.write(JSON.stringify({command,request_id})+'\n');});}
 wait(event,timeout=15000){return new Promise((resolve,reject)=>{const f=v=>{clearTimeout(t);resolve(v)};const t=setTimeout(()=>{this.off(event,f);reject(Error('加载影片超时，请检查文件或网络'))},timeout);this.once(event,f);});}
 async load(file,start=0){const ready=this.wait('file-loaded');try{await this.command(['loadfile',file,'replace',-1,`start=${Math.max(0,start)},pause=yes`]);await ready;}catch(e){ready.catch(()=>{});throw e;}}
 async seek(t){const done=this.wait('playback-restart',12000);try{await this.command(['seek',Math.max(0,t),'absolute+exact']);await done;}catch(e){done.catch(()=>{});throw e;}}
 async close(){if(!this.dead){try{await this.command(['quit']);}catch{} await Promise.race([new Promise(r=>this.proc.once('exit',r)),new Promise(r=>setTimeout(r,2500))]);if(!this.dead)this.proc.kill();}this.socket?.destroy();}
}
module.exports={Player};
