const fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),init=require('sql.js'),{episode,natural,validateNote,url}=require('./core.cjs');
const SOURCES=[{id:'cupfox',name:'茶杯狐',url:'https://cupfox.top/',tag:'影视检索',description:'电影与电视剧检索入口。打开网站查找影片；网站地址、内容与可用性可能变化，可随时修改。'},{id:'archive',name:'Internet Archive',url:'https://archive.org/details/feature_films',tag:'电影档案',description:'长片、早期电影与影像档案，部分条目提供原始文件下载。'},{id:'cctv',name:'央视网',url:'https://tv.cctv.com/',tag:'纪录片 · 剧集',description:'央视节目、纪录片与剧集入口。收藏喜欢的作品，再记录自己的观影感受。'}];
class Store{
 static async open(root){const s=new Store;s.root=root;s.file=path.join(root,'diary.sqlite');fs.mkdirSync(path.join(root,'assets'),{recursive:true});s.SQL=await init();s.db=fs.existsSync(s.file)?new s.SQL.Database(fs.readFileSync(s.file)):new s.SQL.Database();s.db.run('CREATE TABLE IF NOT EXISTS items(id TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS notes(id TEXT PRIMARY KEY,itemId TEXT NOT NULL,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL); PRAGMA user_version=1;');if(s.getSetting('sources')===undefined)s.setting('sources',SOURCES);s.flush();return s;}
 rows(sql,args=[]){const q=this.db.prepare(sql);try{q.bind(args);const a=[];while(q.step())a.push(q.getAsObject());return a;}finally{q.free()}}
 flush(){const tmp=this.file+'.tmp';fs.writeFileSync(tmp,Buffer.from(this.db.export()));fs.renameSync(tmp,this.file);}
 list(){return this.rows('SELECT value FROM items').map(r=>JSON.parse(r.value)).sort((a,b)=>(b.lastPlayed||b.added)-(a.lastPlayed||a.added));}
 get(id){const row=this.rows('SELECT value FROM items WHERE id=?',[id])[0];if(!row)throw Error('找不到这部影片');return JSON.parse(row.value);}
 put(item){this.db.run('INSERT OR REPLACE INTO items VALUES(?,?)',[item.id,JSON.stringify(item)]);this.flush();return item;}
 import(files,{kind='movie',title='',targetId='',media={},category='',allowDuplicate=false}={}){let added=0,skipped=0;const existing=new Set(this.list().flatMap(i=>i.episodes.map(e=>e.path.toLowerCase())));files=files.filter(p=>{if(!allowDuplicate&&existing.has(p.toLowerCase())){skipped++;return false}existing.add(p.toLowerCase());return true;}).sort(natural.compare);const makeEp=p=>({id:randomUUID(),...episode(media[p]?.originalName||p),path:p,...(media[p]||{}),duration:0,position:0,subtitle:'',cues:[]});if(kind==='series'&&files.length){const eps=files.map(makeEp).sort((a,b)=>a.season-b.season||a.episode-b.episode||natural.compare(a.title,b.title));if(targetId){const series=this.get(targetId);if(series.kind!=='series')throw Error('只能把新集数加入剧集');series.episodes.push(...eps);if(String(category).trim())series.category=String(category).slice(0,500);series.episodes.sort((a,b)=>a.season-b.season||a.episode-b.episode||natural.compare(a.title,b.title));if(series.status==='done')series.status='watching';this.put(series);}else this.put({id:randomUUID(),kind,title:title.trim()||path.basename(path.dirname(files[0])),episodes:eps,added:Date.now(),status:'want',rating:0,category:String(category).slice(0,500),review:'',sessions:[]});added=files.length;}else for(const p of files){const ep=makeEp(p);this.put({id:randomUUID(),kind:'movie',title:ep.title,episodes:[ep],added:Date.now(),status:'want',rating:0,category:String(category).slice(0,500),review:'',sessions:[]});added++;}return {added,skipped};}
 update(id,changes){const i=this.get(id);for(const k of ['title','category','review','poster'])if(k in changes)i[k]=String(changes[k]).slice(0,k==='review'?20000:500);if(!i.title.trim())throw Error('片名不能为空');if(['movie','series'].includes(changes.kind))i.kind=changes.kind;if(['want','watching','done'].includes(changes.status))i.status=changes.status;if('rating'in changes)i.rating=Math.max(0,Math.min(5,Number(changes.rating)||0));return this.put(i);}
 progress(id,epId,position,duration,session){const i=this.get(id),ep=i.episodes.find(e=>e.id===epId);if(!ep)return;ep.position=Math.max(0,position||0);ep.duration=duration||ep.duration;if(ep.duration&&ep.position>=ep.duration-2)ep.completed=true;i.lastPlayed=Date.now();i.lastEpisode=ep.id;if(i.status==='want')i.status='watching';if(i.episodes.every(e=>e.completed))i.status='done';if(session&&!(i.sessions||[]).some(s=>s.id===session.id))i.sessions=[...(i.sessions||[]),session];this.put(i);}
 notes(itemId){return this.rows(itemId?'SELECT value FROM notes WHERE itemId=?':'SELECT value FROM notes',itemId?[itemId]:[]).map(r=>JSON.parse(r.value)).sort((a,b)=>b.created.localeCompare(a.created));}
 note(id){return this.notes().find(n=>n.id===id);}
 saveNote(n){n=validateNote(n,this.get(n.itemId));const old=n.id?this.note(n.id):null;if(n.id&&(!old||old.itemId!==n.itemId))throw Error('原笔记已不存在');n={...n,id:old?.id||randomUUID(),created:old?.created||new Date().toISOString(),updated:new Date().toISOString()};this.db.run('INSERT OR REPLACE INTO notes VALUES(?,?,?)',[n.id,n.itemId,JSON.stringify(n)]);this.flush();return n;}
 deleteNote(id){this.db.run('DELETE FROM notes WHERE id=?',[id]);this.flush();}
 remove(id){this.db.run('DELETE FROM notes WHERE itemId=?',[id]);this.db.run('DELETE FROM items WHERE id=?',[id]);this.flush();}
 getSetting(k){const r=this.rows('SELECT value FROM settings WHERE key=?',[k])[0];return r?JSON.parse(r.value):undefined;}
 setting(k,v){this.db.run('INSERT OR REPLACE INTO settings VALUES(?,?)',[k,JSON.stringify(v)]);this.flush();}
 saveSource(s){const list=this.getSetting('sources'),index=list.findIndex(x=>x.id===s.id);const value={id:index<0?randomUUID():s.id,name:String(s.name||'').trim().slice(0,100),url:url(s.url),tag:String(s.tag||'').slice(0,100),description:String(s.description||'').slice(0,2000)};if(!value.name)throw Error('请填写网站名称');if(index<0)list.push(value);else list[index]=value;this.setting('sources',list);return list;}
}
module.exports={Store};
